change file size check (7390-kernel and non-image files would fail here), use better block sizes for faster output, rename variables

diff --git a/toolbox/get_file_from_image b/toolbox/get_file_from_image
--- a/toolbox/get_file_from_image
+++ b/toolbox/get_file_from_image
@@ -100,19 +100,14 @@ if ! tar -t -f "$src" 2>/dev/null 1>&2; then
 	[ $debug -eq 1 ] && printf "The specified file '%s' is not a valid TAR archive.\n" "$src" 1>&2
 	exit 1
 fi
-k="$(tar -t -f "$src" 2>/dev/null | sed -n -e "/$wanted/p")"
-if [ ${#k} -eq 0 ]; then
+f="$(tar -t -f "$src" 2>/dev/null | sed -n -e "/$wanted/p")"
+if [ ${#f} -eq 0 ]; then
 	[ $debug -eq 1 ] && printf "The specified file does not contain a member '%s'." "$wanted" 1>&2
 	exit 1
 fi
-ks="$(tar -t -v -f "$src" "$k" | sed -n -e "s|^\([^ \t]* *\)\{2\}\([^ \t]*\) *.*\$|\2|p")"
-if [ $ks -eq 0 ]; then
-	[ $debug -eq 1 ] && printf "The length of '%s' in the specified file '%s' is 0." "$k" "$src" 1>&2
-	exit 1
-fi
-b=$(( ks / 8 ))
-if [ $(( b * 8 )) -ne $ks ]; then
-	[ $debug -eq 1 ] && printf "The file size of '%s' (%u) isn't a multiple of 8.\n" "$k" $ks 1>&2
+fs="$(tar -t -v -f "$src" "$f" | sed -n -e "s|^\([^ \t]* *\)\{2\}\([^ \t]*\) *.*\$|\2|p")"
+if [ $fs -eq 0 ]; then
+	[ $debug -eq 1 ] && printf "The length of '%s' in the specified file '%s' is 0." "$f" "$src" 1>&2
 	exit 1
 fi
 #######################################################################################################
@@ -138,18 +133,18 @@ trap 'rm $name 2>/dev/null' HUP EXIT INT
 # extract image file, check presence of TI checksum and copy the image file to STDOUT                 #
 #                                                                                                     #
 #######################################################################################################
-tar -x -f "$src" -O "$k" >"$name" 2>/dev/null
+tar -x -f "$src" -O "$f" >"$name" 2>/dev/null
 s=$(stat -c %s "$name")
-if [ $s -ne $ks ]; then
-	[ $debug -eq 1 ] && printf "Error extracting '%s' from '%s', size mismatch.\n" "$k" "$src" 1>&2
+if [ $s -ne $fs ]; then
+	[ $debug -eq 1 ] && printf "Error extracting '%s' from '%s', size mismatch.\n" "$f" "$src" 1>&2
 	exit 1
 fi
 [ $noremove -eq 0 ] && \
-	sig="$(dd if="$name" bs=8 skip=$(( b - 1 )) 2>/dev/null | cmp -l -- - /dev/zero 2>/dev/null | sed -n -e "1,4s|^[ \t]*. *\([0-7]*\).*\$|\1|p" | sed -e ':x;$!N;s|\n| |;tx')" || \
+	sig="$(dd if="$name" bs=$(( fs - 8 )) skip=1 2>/dev/null | cmp -l -- - /dev/zero 2>/dev/null | sed -n -e "1,4s|^[ \t]*. *\([0-7]*\).*\$|\1|p" | sed -e ':x;$!N;s|\n| |;tx')" || \
 	sig="none"
 if [ "$sig" = "43 336 123 304" ]; then
-	[ $debug -eq 1 ] && printf "A TI checksum signature was found on '%s', file will be truncated by 8 byte.\n" "$k" 1>&2
-	dd if="$name" bs=8 count=$(( b - 1 )) 2>/dev/null
+	[ $debug -eq 1 ] && printf "A TI checksum signature was found on '%s', file will be truncated by 8 byte.\n" "$f" 1>&2
+	dd if="$name" bs=$(( fs - 8 )) count=1 2>/dev/null
 else
 	cat "$name" 2>/dev/null # it's faster than 'dd' for the complete file
 fi
