determine sysfs mount point, add bridge functions

diff --git a/helpers/yourfritz_helpers b/helpers/yourfritz_helpers
--- a/helpers/yourfritz_helpers
+++ b/helpers/yourfritz_helpers
@@ -439,6 +439,29 @@ yf_uppercase()
 }
 #######################################################################################
 #
+# sysfs - get sysfs mount point from /proc/mounts
+#
+# parameters:
+#   none
+#
+# stdout:
+#   the path, where the sysfs is mounted
+#
+# return code:
+#   0 - stdout value is valid
+#   1 - error occured, sysfs isn't mounted or procfs isn't available
+#
+#######################################################################################
+yf_sysfs()
+{
+	local rc=0 mp
+	mp="$(sed -n -e "s|^sysfs \([^ ]*\) .*|\1|p" /proc/mounts | sed -n -e "1p")"
+	[ ${#mp} -eq 0 ] && return 1
+	echo "$mp"
+	return 0
+}
+#######################################################################################
+#
 # pack - create a packed complex data structure from basic data types
 #
 # parameters:
@@ -569,7 +592,8 @@ yf_print_ip()
 #######################################################################################
 yf_network_interfaces()
 {
-	local sysfs=/sys
+	local sysfs
+	sysfs="$(yf_sysfs || printf "/sys")"
 	find $sysfs/devices/virtual/net/ -maxdepth 1 -type d -print \
 		| sed -e "s|^$sysfs/devices/virtual/net/||" -e '/^$/d' -e '/^lo$/d' \
 		| sed -e ':x;$!N;s/\n/ /;tx'
@@ -591,7 +615,8 @@ yf_network_interfaces()
 #######################################################################################
 yf_wireless_interfaces()
 {
-	local sysfs=/sys
+	local sysfs
+	sysfs="$(yf_sysfs || printf "/sys")"
 	find $sysfs/devices/virtual/net/*/wireless -maxdepth 1 -type d -print \
 		| sed -e "s|^$sysfs/devices/virtual/net/\([^/]*\)/wireless\$|\1|" -e '/^$/d' \
 		| sed -e ':x;$!N;s/\n/ /;tx'
@@ -613,7 +638,8 @@ yf_wireless_interfaces()
 #######################################################################################
 yf_bridge_interfaces()
 {
-	local sysfs=/sys
+	local sysfs
+	sysfs="$(yf_sysfs || printf "/sys")"
 	find $sysfs/devices/virtual/net/*/bridge -maxdepth 1 -type d -print \
 		| sed -e "s|^$sysfs/devices/virtual/net/\([^/]*\)/bridge\$|\1|" -e '/^$/d' \
 		| sed -e ':x;$!N;s/\n/ /;tx'
@@ -633,7 +659,8 @@ yf_bridge_interfaces()
 #######################################################################################
 yf_is_wireless_interface()
 {
-	local sysfs=/sys intf="$1"
+	local intf="$1" sysfs
+	sysfs="$(yf_sysfs || printf "/sys")"
 	[ -d $sysfs/devices/virtual/net/$intf/wireless ] && return 0 || return 1
 }
 #######################################################################################
@@ -650,7 +677,51 @@ yf_is_wireless_interface()
 #######################################################################################
 yf_is_bridge_interface()
 {
-	local sysfs=/sys intf="$1"
+	local intf="$1" sysfs
+	sysfs="$(yf_sysfs || printf "/sys")"
 	[ -d $sysfs/devices/virtual/net/$intf/bridge ] && return 0 || return 1
+}
+#######################################################################################
+#
+# is_bridge_member - check, if the specified interface is a bridge member without an
+#                    own IP address
+#
+# parameters:
+#   $1 - interface to be checked
+#
+# return code:
+#   0 - the interface is a brigde member
+#   1 - the interface isn't a bridge member
+#
+#######################################################################################
+yf_is_bridge_member()
+{
+	local intf="$1" sysfs
+	sysfs="$(yf_sysfs || printf "/sys")"
+	[ -d $sysfs/devices/virtual/net/$intf/brport ] && return 0 || return 1
+}
+#######################################################################################
+#
+# get_bridge - retrieve the bridge interface name for the specified interface, if any
+#
+# parameters:
+#   $1 - interface to be checked
+#
+# stdout:
+#   the name of the bridge, where the specified interface is a member
+#
+# return code:
+#   0 - the interface is a brigde member, stdout is valid
+#   1 - the interface isn't a bridge member
+#
+#######################################################################################
+yf_get_bridge()
+{
+	local intf="$1" sysfs
+	sysfs="$(yf_sysfs || printf "/sys")"
+	[ -d $sysfs/devices/virtual/net/$intf/brport ] || return 1
+	readlink $sysfs/devices/virtual/net/$intf/brport/bridge \
+		| sed -e "s|.*/\(.*\)\$|\1|"
+	return 0
 }
 
