add host from subnet functions

diff --git a/helpers/yourfritz_helpers b/helpers/yourfritz_helpers
--- a/helpers/yourfritz_helpers
+++ b/helpers/yourfritz_helpers
@@ -1,3 +1,5 @@
+#! /bin/true
+# vi: set tabstop=4 syntax=sh : # colorize it in 'vi' and use shorter tabstops
 #######################################################################################
 #
 # summarize some often needed helper (shell) functions, which provide replacements
@@ -205,7 +207,7 @@ yf_index_of()
 #
 # parameters:
 #   $1 - input value (string representing a decimal)
-#   $2 - length (in bytes) to be used for the output (the resulting string will use
+#   $2 - length (in bytes) to use for the output (the resulting string will use
 #        this value * 2, because each output byte consists of two nibbles); if this
 #        parameter is not specified, the needed length is determined by the value
 #
@@ -847,6 +849,78 @@ yf_get_default_gateway_interface()
 	intf="$(sed -n -e "s|\([^\t]*\)\t*0\{8\}\t*[^\t]*\t*.*0\{8\}\t*.*\$|\1|p" /proc/net/route)"
 	[ ${#intf} -eq 0 ] && return 1
 	echo "$intf"
+	return 0
+}
+#######################################################################################
+#
+# get_first_host_in_subnet - compute the first usable IPv4 address in the specified
+#                            subnet
+#
+# parameters:
+#   $1 - the subnet to use for computations in dotted decimal notation with mask suffix
+#
+# stdout:
+#   the first usable host address (as hexadecimal string)
+#
+# return code:
+#   0 - stdout is valid
+#   1 - parameter error
+#
+# remarks:
+#   The first address (all unmasked bits set to zero) is interpreted as the 'network'
+#   address and is skipped. There's no usable result with a mask greater than 30,
+#   because the possible two addresses with a 31-bit mask can't form a valid subnet.
+#
+#######################################################################################
+yf_get_first_host_in_subnet()
+{
+	local in="$1" addr bits mask inv_mask addr_dec res
+	addr="${in%%/*}"
+	bits="${in#*/}"
+	yf_is_decimal "$bits" || return 1
+	[ $bits -le 1 -o $bits -gt 30 ] && return 1
+	addr="$(yf_ipv4addr "$addr")"
+	inv_mask=$(( ( 1 << ( 32 - $bits ) ) - 1 ))
+	mask=$(( ~inv_mask ))
+	addr_dec=$(yf_hex2dec "$addr")
+	res=$(( ( addr_dec & mask ) + 1 ))
+	yf_dec2hex "$res"
+	return 0
+}
+#######################################################################################
+#
+# get_last_host_in_subnet - compute the last usable IPv4 address in the specified
+#                           subnet
+#
+# parameters:
+#   $1 - the subnet to use for computations in dotted decimal notation with mask suffix
+#
+# stdout:
+#   the last usable host address (as hexadecimal string)
+#
+# return code:
+#   0 - stdout is valid
+#   1 - parameter error
+#
+# remarks:
+#   The really last address (all unmasked bits set to one) is interpreted as the 
+#   'broadcast' address and is skipped. There's no usable result with a mask greater 
+#   than 30, because the possible two addresses with a 31-bit mask can't form a valid
+#   subnet.
+#
+#######################################################################################
+yf_get_last_host_in_subnet()
+{
+	local in="$1" addr bits mask inv_mask addr_dec res
+	addr="${in%%/*}"
+	bits="${in#*/}"
+	yf_is_decimal "$bits" || return 1
+	[ $bits -le 1 -o $bits -gt 30 ] && return 1
+	addr="$(yf_ipv4addr "$addr")"
+	inv_mask=$(( ( 1 << ( 32 - $bits ) ) - 1 ))
+	addr_dec=$(yf_hex2dec "$addr")
+	res=$(( ( addr_dec | inv_mask ) - 1 ))
+	yf_dec2hex "$res"
 	return 0
 }
 
