change public key source handling
and add AVM's builtin keys from firmware version 84.06.51 to
the script

diff --git a/signimage/check_signed_image b/signimage/check_signed_image
--- a/signimage/check_signed_image
+++ b/signimage/check_signed_image
@@ -18,6 +18,7 @@
 #   8 - the signature file contains no ASN.1 structure                             #
 #   9 - the signature file uses an unsupported hash algorithm                      #
 #  10 - the hash algorithm used to sign isn't supported by the openssl binary      #
+#  11 - none of the specified public key sources was able to provide a key         #
 #  32 - "openssl" binary not found                                                 #
 #  33 - "openssl" function "dgst" is not available                                 #
 #  34 - "openssl" function "rsautl" is not available                               #
@@ -51,11 +52,18 @@ usage()
 {
 	echo -e "\x1B[1mCheck, if the signature of the specified image file is valid.\x1B[0m\n"
 	echo -e "Usage:\n"
-	echo -e "$0 \x1B[1mimagefile\x1B[0m { -f \x1B[1mpubkey_list_file\x1B[0m | \x1B[1mpubkey_file\x1B[0m }\n"
-	echo -e "\x1B[1mimagefile\x1B[0m is the archive to check and \x1B[1mpubkey_list_file\x1B[0m has"
-	echo -e "to contain the name(s) of possible public key files, one name per line."
-	echo -e "If you know the right public key for sure, you may specify its file name"
-	echo -e "instead of using a list."
+	echo -e "$0 \x1B[1mimagefile\x1B[0m \x1B[1mpublickey_source\x1B[0m [...]\n"
+	echo -e "\x1B[1mimagefile\x1B[0m is the archive to check and the list of public keys to consider"
+	echo -e "for decryption may be built from the following sources:"
+	echo -e ""
+	echo -e "-f \x1B[1mfilename\x1B[0m - add the file names in the specified file"
+	echo -e "-b          - add AVM default keys (avm_firmware_public_key[1-3] and"
+	echo -e "              plugin_global_key.pem) to considerations"
+	echo -e "\x1B[1mfilename\x1B[0m    - add the specified file to the list"
+	echo -e ""
+	echo -e "The first key from the specified sources (which are probed in the"
+	echo -e "given order) able to decode the signature file will be used for"
+	echo -e "signature verification."
 	echo -e ""
 	echo -e "Remark:"
 	echo -e "If you have an image file not signed by AVM, it may use better hash"
@@ -64,6 +72,40 @@ usage()
 	echo -e "The algorithm used to create the signature (by the signer) is detected"
 	echo -e "while decoding the signature file in a first step (its format will be"
 	echo -e "checked too in this step)."
+}
+####################################################################################
+#                                                                                  #
+# output the lines to use the builtin keys from AVM images - taken from the files  #
+# /etc/avm_firmware_public_keys[1-3] and in /etc/plugin_global_key.pem in current  #
+# firmware for the 7390 model (84.06.51)                                           #
+#                                                                                  #
+####################################################################################
+builtin_keys()
+{
+	local avm1="DESC=\"AVM default key 1\" SRC=\"avm_firmware_public_key1\" MOD=\"\
+00ab54b73f000e9fc5bf3c0d229e56ae1644507877ca1eaf364708975de1e50236754fdc8577bd9e9e\
+c4c94bd595c22195a9cfa2ac57840c507b483ccf1c5d4d1448c6d8c8bdab629df4e5bcd65a52695064\
+819d1f5157afeb8fea43dedd9c7b091c344cfb42434f5f7bc77bbf2c0469400d10a29d04d6c1b2807f\
+d3be68800eaf\" EXP=\"010001\""
+	local avm2="DESC=\"AVM default key 2\" SRC=\"avm_firmware_public_key2\" MOD=\"\
+00c923d6cde5ca1780e84b6383c6c24b03a56532149f0a210541f16b1698d5761dd90ffd77500ff5dd\
+2c9269710dad5ebcb1f6fbf318993429fcb228c043cc0980ec09b85b8a393c96b3e52f647b898ddff3\
+7aa9f662771aa87cee8686d3e2e3970a38e25bdc13f591344a2f6a39647a6555696fca21423e90c987\
+e990ad64ff81\" EXP=\"010001\""
+	local avm3="DESC=\"AVM default key 3\" SRC=\"avm_firmware_public_key3\" MOD=\"\
+00f2ee9ffd8556211f5644da48a252b107124b330d4c20dcf3b9bac892924cabaa4df4f53e1c62e3f2\
+aa12a23eb1d770df1520a998078738407e6a71b077f73ba976363836b880b0dd88741bc3b83ab06169\
+1226e823404b7fc88ed278d8130fe5336eb925c78f2f8ad7cb87d9586286f768ab3236fa8fb51ae7c4\
+bbe1e041d849\" EXP=\"010001\""
+	local plugin="DESC=\"AVM plugin key\" SRC=\"plugin_global_key.pem\"     MOD=\"\
+00bed5268d38b33fe9876f4ae22a5970657c3501adcb84879654def6fc83c1303667b12a031025782c\
+b6490fed946ec81c3968ebc5d50697af9a2475339692eb5c84240cac09b2b3ca2a419efb6ae206e782\
+209fc5a405054630634d4a4bb0f3c053c72547f2fb95add232929a7f722db94d873e02cbb2985106d6\
+dd66dfa5592f\" EXP=\"010001\""
+	echo "$avm1"
+	echo "$avm2"
+	echo "$avm3"
+	echo "$plugin"
 }
 ####################################################################################
 #                                                                                  #
@@ -233,37 +275,54 @@ seek_image=$(( HEADER / 512 ))
 skip_blocks=$BLOCKS
 ####################################################################################
 #                                                                                  #
-# check, if we have a single public key file or a list of possible candidates      #
+# copy the specified public keys from different sources to our temporary key list  #
 #                                                                                  #
 ####################################################################################
-if [ -z $2 ]; then
+touch "$tmp/public_keys"
+shift
+if [ -z $1 ]; then
 	usage 1>&2
 	exit 2
 fi
-if [ "$2" == "-f" ]; then
-	multiple_keys=1
-	if [ -z "$3" ]; then
-		usage 1>&2
-		exit 2
-	fi
-	if ! [ -f "$3" ]; then
-		echo -e "The specified public key list file \x1B[1m$3\x1B[0m does not exist." 1>&2
-		exit 6
-	fi
-	while read filename; do
-		if [ -f "$filename" ]; then
-			mod=$(sed -n -e "1p" "$filename")
-			exp=$(sed -n -e "2p" "$filename")
-			[ ${#exp} -eq 0 ] && exp=010001
-			echo "DESC=\"\" SRC=\"$filename\" MOD=$mod EXP=$exp" >>"$tmp/public_keys"
-		fi
-	done <"$3"
-else
-	multiple_keys=0
-	mod=$(sed -n -e "1p" "$2")
-	exp=$(sed -n -e "2p" "$2")
-	[ ${#exp} -eq 0 ] && exp=010001
-	echo "DESC=\"from command line\" SRC=\"$2\" MOD=$mod EXP=$exp" >>"$tmp/public_keys"
+while [ "$#" -gt 0 ]; do
+	case "$1" in
+		"-f")
+			if [ -z "$2" ]; then
+				echo "Missing filename after -f option." 1>&2
+				exit 2
+			fi
+			if ! [ -f "$2" ]; then
+				echo -e "The specified public key list file \x1B[1m$2\x1B[0m does not exist." 1>&2
+				exit 6
+			fi
+			while read filename; do
+				if [ -f "$filename" ]; then
+					mod=$(sed -n -e "1p" "$filename")
+					exp=$(sed -n -e "2p" "$filename")
+					[ ${#exp} -eq 0 ] && exp=010001
+					echo "DESC=\"\" SRC=\"$filename\" MOD=$mod EXP=$exp" >>"$tmp/public_keys"
+				fi
+			done <"$2"
+			shift 2
+			;;
+		"-b")
+			builtin_keys >>"$tmp/public_keys"
+			shift
+			;;	
+		*)
+			mod=$(sed -n -e "1p" "$1")
+			exp=$(sed -n -e "2p" "$1")
+			if [ ${#mod} -gt 0 ]; then
+				[ ${#exp} -eq 0 ] && exp=010001
+				echo "DESC=\"command line\" SRC=\"$1\" MOD=$mod EXP=$exp" >>"$tmp/public_keys"
+			fi
+			shift
+			;;
+	esac
+done
+if ! [ -s "$tmp/public_keys" ]; then
+	echo "None of the specified public key files could be loaded." 1>&2
+	exit 11
 fi
 ####################################################################################
 #                                                                                  #
@@ -271,8 +330,8 @@ fi
 # public key specified, until the usable was found or the end of list is reached   #
 #                                                                                  #
 ####################################################################################
-if [ $multiple_keys -eq 1 ]; then
-	echo -e "Trying to determine the correct key ... " 1>&2
+if [ $(sed -n -e "\$=" "$tmp/public_keys") -gt 1 ]; then
+	echo -e "Trying to determine the correct key now ..." 1>&2
 fi
 key_found=0
 valid_algo=0
@@ -301,6 +360,7 @@ while read line; do
 				rc=$?
 				if [ $rc -eq 0 ]; then
 					show_ok
+					break
 				else
 					show_error
 					exit 10
