add the ability to sign with box key
- the scripts to sign and verify a TAR file may now be used
  to sign with the RSA key from FRITZ!OS and to verify such
  signatures, please read the usage explanations

diff --git a/signimage/check_signed_image b/signimage/check_signed_image
--- a/signimage/check_signed_image
+++ b/signimage/check_signed_image
@@ -2,8 +2,8 @@
 ####################################################################################
 #                                                                                  #
 # check, if the specified image contains an AVM-like signature and if it is signed #
-# with a key from the specified list of possible public key files (containing the  #
-# public keys in AVM's format)                                                     #
+# with a key from the specified list of possible public key files (the public keys #
+# may be specified/used in various format, please read the usage output carefully) #
 #                                                                                  #
 # The result of this check is written to STDERR and the return code is set to one  #
 # of the values below:                                                             #
@@ -23,9 +23,11 @@
 #  12 - a specified file contains invalid data                                     #
 #  13 - the builtin key files from FRITZ!OS (option -b) can only be used, if we're #
 #       running in the correct environment (or a valid emulation of such one)      #
+#  14 - unable to read the FRITZ!OS RSA key from /var/flash                        #
 #  32 - "openssl" binary not found                                                 #
 #  33 - "openssl" function "dgst" is not available                                 #
 #  34 - "openssl" function "rsautl" is not available                               #
+#  35 - "openssl" function "x509" is needed and not available                      #
 #  64 - signature verification failed                                              #
 #                                                                                  #
 ####################################################################################
@@ -35,6 +37,9 @@
 ####################################################################################
 avm_default_files="/etc/avm_firmware_public_key[1-9] plugin_global_key.pem"
 eva_prompt="Eva_AVM"
+box_key_name="/var/flash/websrv_ssl_key.pem"
+box_cert_name1="/var/flash/websrv_ssl_cert.pem"
+box_cert_name2="/var/tmp/websrv_ssl_cert.pem"
 ####################################################################################
 #                                                                                  #
 # some subfunctions                                                                #
@@ -47,7 +52,7 @@ show_version()
 	local v
 	v=$(openssl version 2>/dev/null)
 	if [ $? -eq 127 ]; then
-		echo -e "Missing 'openssl' binary." 1>&2
+		echo -e "Missing \x1B[1mopenssl\x1B[0m binary." 1>&2
 		return 1
 	else
 		echo -e "Found \x1B[1;34m$v\x1B[0m" 1>&2
@@ -69,16 +74,6 @@ usage()
 	echo -e "sources:"
 	echo -e ""
 	echo -e "-f \x1B[1mfilename\x1B[0m - add the file names in the specified file"
-#	echo -e "-m \x1B[1mmajor\x1B[0m    - add AVM's default keys (avm_firmware_public_key[1-9] for the"
-#	echo -e "              specified device (major version) to the list, requires the sqlite3"
-#	echo -e "              database with the keys and adds all public keys (version doesn't"
-#	echo -e "              matter) ever seen for this model - even the known plugin signing"
-#	echo -e "              keys"
-#	echo -e "-k \x1B[1mindex\x1B[0m    - add only the key with the specified index from the"
-#	echo -e "              sqlite3 database as consideration, index may be taken from the"
-#	echo -e "              database listing displayed with the '-l' option"
-#	echo -e "-l            show a list of keys from the sqlite3 database, you have to use"
-#	echo -e "              external filters to restrict output volume"
 	echo -e "-b          - add the key files from the current OS to the list, this option"
 	echo -e "              makes only sense, if the script is executed on a FRITZ!OS-based"
 	echo -e "              device or in a proper emulation; an existing plugin signing key"
@@ -90,6 +85,9 @@ usage()
 	echo -e "-a \x1B[1mfilename\x1B[0m - add the specified file (AVM text format) to the list"
 	echo -e "-p \x1B[1mfilename\x1B[0m - add the specified file (PEM format) to the list"
 	echo -e "-d \x1B[1mfilename\x1B[0m - add the specified file (DER format) to the list"
+	echo -e "-s          - check, that the image file was signed with the RSA key from"
+	echo -e "              the box where we're running on (cannot be combined with other"
+	echo -e "              key sources)"
 	echo -e ""
 	echo -e "The first key from the specified sources (which are probed in the"
 	echo -e "given order) able to decode the signature file will be used for"
@@ -112,38 +110,8 @@ usage()
 }
 ####################################################################################
 #                                                                                  #
-# output the lines to use the builtin keys from AVM images - taken from the files  #
-# /etc/avm_firmware_public_keys[1-3] and in /etc/plugin_global_key.pem in current  #
-# firmware for the 7390 model (84.06.51) - is only a shortcut to get the keys for  #
-# development tests without the needs to carry them around as single files         #
-#                                                                                  #
-####################################################################################
-builtin_keys_for_test()
-{
-	local avm1="DESC=\"AVM default key 1\" SRC=\"avm_firmware_public_key1\" MOD=\"\
-00ab54b73f000e9fc5bf3c0d229e56ae1644507877ca1eaf364708975de1e50236754fdc8577bd9e9e\
-c4c94bd595c22195a9cfa2ac57840c507b483ccf1c5d4d1448c6d8c8bdab629df4e5bcd65a52695064\
-819d1f5157afeb8fea43dedd9c7b091c344cfb42434f5f7bc77bbf2c0469400d10a29d04d6c1b2807f\
-d3be68800eaf\" EXP=\"010001\""
-	local avm2="DESC=\"AVM default key 2\" SRC=\"avm_firmware_public_key2\" MOD=\"\
-00c923d6cde5ca1780e84b6383c6c24b03a56532149f0a210541f16b1698d5761dd90ffd77500ff5dd\
-2c9269710dad5ebcb1f6fbf318993429fcb228c043cc0980ec09b85b8a393c96b3e52f647b898ddff3\
-7aa9f662771aa87cee8686d3e2e3970a38e25bdc13f591344a2f6a39647a6555696fca21423e90c987\
-e990ad64ff81\" EXP=\"010001\""
-	local avm3="DESC=\"AVM default key 3\" SRC=\"avm_firmware_public_key3\" MOD=\"\
-00f2ee9ffd8556211f5644da48a252b107124b330d4c20dcf3b9bac892924cabaa4df4f53e1c62e3f2\
-aa12a23eb1d770df1520a998078738407e6a71b077f73ba976363836b880b0dd88741bc3b83ab06169\
-1226e823404b7fc88ed278d8130fe5336eb925c78f2f8ad7cb87d9586286f768ab3236fa8fb51ae7c4\
-bbe1e041d849\" EXP=\"010001\""
-	echo "$avm1"
-	echo "$avm2"
-	echo "$avm3"
-}
-####################################################################################
-#                                                                                  #
-# output the lines to use the builtin keys from the FRITZ!OS system, this script   #
-# is running on - any further search will be skipped, if the environment does not  #
-# match the usual characteristics of a FRITZ!Box router or a FRITZ!Repeater device #
+# try to identify FRITZ!OS as runtime environment (not too sophisticated, but it   #
+# should be able to make this distinction)                                         #
 #                                                                                  #
 # The FRITZ!OS will be identified by looking for the environment variables:        #
 # HWRevision, CONFIG_ENVIRONMENT_PATH                                              #
@@ -152,9 +120,9 @@ bbe1e041d849\" EXP=\"010001\""
 # environment and finally the content of 'prompt' is checked for 'Eva_AVM'         #
 #                                                                                  #
 ####################################################################################
-builtin_keys()
+is_fritzos_environment()
 {
-	local rc=13
+	local rc=1
 	[ ${#HWRevision} -eq 0 ] && return $rc
 	[ ${#CONFIG_ENVIRONMENT_PATH} -eq 0 ] && return $rc
 	[ -d "$CONFIG_ENVIRONMENT_PATH" ] || return $rc
@@ -165,6 +133,19 @@ builtin_keys()
 	local prompt="$(sed -n -e "s|^prompt\t\(.*\)\$|\1|p" $CONFIG_ENVIRONMENT_PATH/environment)"
 	[ ${#prompt} -eq 0 ] && return $rc
 	[ "$prompt" != "$eva_prompt" ] && return $rc
+	return 0
+}
+####################################################################################
+#                                                                                  #
+# output the lines to use the builtin keys from the FRITZ!OS system, this script   #
+# is running on - any further search will be skipped, if the environment does not  #
+# match the usual characteristics of a FRITZ!Box router or a FRITZ!Repeater device #
+#                                                                                  #
+####################################################################################
+builtin_keys()
+{
+	local rc=13
+	is_fritzos_environment || return $rc
 	local f mod exp
 	rc=0
 	for f in $avm_default_files; do
@@ -175,6 +156,66 @@ builtin_keys()
 			echo "DESC=\"current system\" SRC=\"$f\" MOD=$mod EXP=$exp" >>"$tmp/public_keys"
 		fi
 	done
+	return $rc
+}
+####################################################################################
+#                                                                                  #
+# output the modulus from the RSA key in /var/flash/websrv_ssl_key.pem to the list #
+#                                                                                  #
+# We'll try to extract the modulus from the private key first, if we cannot read   #
+# this key due to missing or wrong password, we'll extract it from the X.509       #
+# certificate in /var/flash or /var/tmp.                                           #
+#                                                                                  #
+####################################################################################
+read_box_key()
+{
+	local rc=14 pkp found
+	pkp=$(which privatekeypassword)
+#	found=$?
+	found=1
+	if [ $found -eq 0 ]; then
+		openssl rsa -in $box_key_name -pubout -passin pass:"$(privatekeypassword)" -out "$tmp/pubkey" 2>/dev/null
+		if [ $? -eq 0 ]; then
+			read_openssl_file "$tmp/pubkey" PEM "box key" "FRITZ!OS RSA key"
+			[ $? -ne 0 ] && found=1
+		else
+			found=1
+		fi
+	fi
+	if [ $found -ne 0 ]; then # try to use the certificate to get the public key
+		echo -en "Check \x1B[1mx509\x1B[0m command ... " 1>&2
+		echo "" | openssl x509 2>&1 | grep -q '^unable to load certificate' 2>/dev/null 1>&2
+		rc=$?
+		if [ $rc -eq 0 ]; then
+			show_ok 
+		else
+			show_error
+			return 35
+		fi
+		if [ $rc -eq 0 ]; then
+			echo -ne "Trying to read public key from \x1B[1m$box_cert_name1\x1B[0m ... " 1>&2
+			openssl x509 -in $box_cert_name1 -pubkey -noout >"$tmp/pubkey" 2>/dev/null
+			if [ $? -ne 0 ]; then
+				show_error
+				echo -ne "Trying to read public key from \x1B[1m$box_cert_name2\x1B[0m ... " 1>&2
+				openssl x509 -in $box_cert_name2 -pubkey -noout >"$tmp/pubkey" 2>/dev/null
+				if [ $? -ne 0 ]; then
+					show_error 
+					rc=14
+				else
+					show_ok
+					rc=0
+				fi				
+			else
+				show_ok
+				rc=0
+			fi
+			if [ $rc -eq 0 ]; then
+				read_openssl_file "$tmp/pubkey" PEM "box certificate" "FRITZ!OS certificate"
+				rc=$?
+			fi
+		fi	
+	fi
 	return $rc
 }
 ####################################################################################
@@ -238,17 +279,17 @@ modulus_to_der()
 ####################################################################################
 read_openssl_file()
 {
-	local file="$1" format="$2" rc=12 line MODULUS EXPONENT Modulus
+	local file="$1" format="$2" desc="${3:-$format key}" display="${4:-$file}" rc=12 line MODULUS EXPONENT Modulus
 	line=$(openssl rsa -in "$file" -pubin -inform $format -modulus -noout 2>/dev/null)
 	rc=$?
 	if [ $rc -ne 0 ]; then
-		echo "Unable to read RSA key ($format) from input file '$file'." 1>&2
+		echo -e "Unable to read RSA key ($format) from input file \x1B[1m$file\x1B[0m." 1>&2
 		return $rc
 	else
 		eval $line
 		MODULUS="$(echo "$Modulus" | sed -e "y/ABCDEF/abcdef/")"
 		if [ ${#MODULUS} -eq 0 ]; then
-			echo "Unable to read RSA key ($format) from input file '$file'." 1>&2
+			echo "Unable to read RSA key ($format) from input file \x1B[1m$file\x1B[0m." 1>&2
 			return $rc
 		fi
 		first=${MODULUS:0:1}
@@ -259,7 +300,7 @@ read_openssl_file()
 			EXPONENT=$(openssl rsa -in "$file" -pubin -inform $format -text -noout |
 			sed -n -e "s|^Exponent: [0-9]* (\(0x[0-9a-fA-F]*\))\$|\1|p")
 			if [ ${#EXPONENT} -eq 0 ]; then
-				echo "Unexpected output from public key file '$file' ($format)." 1>&2
+				echo "Unexpected output from public key file \x1B[1m$file\x1B[0m ($format)." 1>&2
 				return $rc
 			fi
 			EXPONENT=$(printf "%016x" $(( EXPONENT )))
@@ -270,7 +311,7 @@ read_openssl_file()
 		else
 			EXPONENT=010001
 		fi
-		echo "DESC=\"$format key\" SRC=\"$file\" MOD=$MODULUS EXP=$EXPONENT"
+		echo "DESC=\"$desc\" SRC=\"$display\" MOD=$MODULUS EXP=$EXPONENT"
 	fi
 }
 ####################################################################################
@@ -295,7 +336,7 @@ fi
 ####################################################################################
 show_version
 [ $? -ne 0 ] && exit 32
-echo -en "Check 'dgst' command ... " 1>&2
+echo -en "Check \x1B[1mdgst\x1B[0m command ... " 1>&2
 echo "" | openssl dgst 2>&1 | grep -q '^(stdin)=' 2>/dev/null 1>&2
 rc=$?
 if [ $rc -eq 0 ]; then
@@ -304,7 +345,7 @@ else
 	show_error
 	exit 33
 fi
-echo -en "Check 'rsautl' command ... " 1>&2
+echo -en "Check \x1B[1mrsautl\x1B[0m command ... " 1>&2
 echo "" | openssl rsautl 2>&1 | grep -q '^no keyfile specified' 2>/dev/null 1>&2
 rc=$?
 if [ $rc -eq 0 ]; then
@@ -326,18 +367,18 @@ trap "rm -r \"$tmp\"" EXIT HUP INT
 # If the signature isn't the last file (we've checked the length already), we have #
 # to find the offset of the last member with the signature name - the last one is  #
 # important, because the archive may contain more than one member with the same    #
-# name and the last one will overwrite all previously extracted files ... we need  #
-# more space at the filesystem, if we must create a "phantom file" to be used with #
-# the digest computation.                                                          # 
+# name and the last one will overwrite all previously extracted files.             #
+#                                                                                  # 
 # Here we could try to find the member name in the file content, but this would be #
 # impossible with "normal" commands (I don't know any applet, which may find a     #
 # string in a binary file and return the offsets of these strings) and searching   #
 # a hexdump output is really boring and much too slow.                             #
+#                                                                                  #
 # A better approach should be to count the archive members from start of file and  #
 # to compute their respective offsets - we're interested in the last occurence of  #
 # ./var/signature only.                                                            #
 # We compute the offset and size of every member here, it makes things easier      #
-# while checking the signature presence and format.                                #
+# while checking signature's presence and format.                                  #
 #                                                                                  #
 ####################################################################################
 offset=0
@@ -398,7 +439,7 @@ while [ "$#" -gt 0 ]; do
 	case "$1" in
 		"-f")
 			if [ -z "$2" ]; then
-				echo "Missing filename after -f option." 1>&2
+				echo -e "Missing filename after \x1B[1m-f\x1B[0m option." 1>&2
 				exit 2
 			fi
 			if ! [ -f "$2" ]; then
@@ -419,14 +460,14 @@ while [ "$#" -gt 0 ]; do
 			builtin_keys >>"$tmp/public_keys"
 			rc=$?
 			if [ $rc -ne 0 ]; then
-				echo "The option -b may only be used on a FRITZ!OS device." 1>&2
+				echo -e "The option \x1B[1m-b\x1B[0m may only be used on a FRITZ!OS device." 1>&2
 				exit $rc
 			fi
 			shift
 			;;	
 		"-c")
 			if [ -z "$2" ]; then
-				echo "Missing filename after -c option." 1>&2
+				echo -e "Missing filename after \x1B[1m-c\x1B[0m option." 1>&2
 				exit 2
 			fi
 			if ! [ -f "$2" ]; then
@@ -438,7 +479,7 @@ while [ "$#" -gt 0 ]; do
 			;;
 		"-a")
 			if [ -z "$2" ]; then
-				echo "Missing filename after -a option." 1>&2
+				echo -e "Missing filename after \x1B[1m-a\x1B[0m option." 1>&2
 				exit 2
 			fi
 			if ! [ -f "$2" ]; then
@@ -455,7 +496,7 @@ while [ "$#" -gt 0 ]; do
 			;;
 		"-p"|"-d")
 			if [ -z "$2" ]; then
-				echo "Missing filename after $1 option." 1>&2
+				echo -e "Missing filename after \x1B[1m$1\x1B[0m option." 1>&2
 				exit 2
 			fi
 			[ "$1" == "-p" ] && format="PEM" || format="DER"
@@ -469,15 +510,37 @@ while [ "$#" -gt 0 ]; do
 			fi
 			shift 2
 			;;
+		"-s")
+			if ! [ -z "$2" ]; then
+				echo -e "Extra data specified after \x1B[1m$1\x1B[0m option." 1>&2
+				exit 2
+			fi
+			if ! is_fritzos_environment; then
+				echo -e "The option \x1B[1m-s\x1B[0m may only be used on a FRITZ!OS device." 1>&2
+				exit 2
+			fi
+			if [ -s "$tmp/public_keys" ]; then
+				cat $tmp/public_keys
+				echo -e "The option \x1B[1m-s\x1B[0m may only be used without any other keys." 1>&2
+				exit 2
+			fi
+			read_box_key >>"$tmp/public_keys"
+			rc=$?
+			if [ $rc -ne 0 ]; then
+				echo -e "Unable to read the RSA key from the FRITZ!OS device." 1>&2
+				exit $rc
+			fi
+			shift
+			;;
 		*)
-			echo -e "Unknown option '$1' specified on command line." 1>&2
+			echo -e "Unknown option \x1B[1m$1\x1B[0m specified on command line." 1>&2
 			usage 1>&2
 			exit 1
 			;;
 	esac
 done
 if ! [ -s "$tmp/public_keys" ]; then
-	echo "None of the specified public key files could be loaded." 1>&2
+	echo -e "None of the specified public key files could be loaded." 1>&2
 	exit 11
 fi
 ####################################################################################
@@ -503,7 +566,7 @@ while read line; do
 		show_ok
 		algo=$(echo "$output" | sed -n -e "s|^.*OBJECT.*:\(.*\)\$|\1|p" 2>/dev/null)
 		if [ ${#algo} -gt 0 ]; then
-			echo -en "Checking support for the used hash algorithm '$algo' ... " 1>&2
+			echo -en "Checking support for the used hash algorithm \x1B[1m$algo\x1B[0m ... " 1>&2
 			valid_algo=0
 			for a in md5 sha1 sha224 sha256 sha384 sha512 whirlpool; do
 				if [ "$a" == "$algo" ]; then
diff --git a/signimage/generate_signing_key b/signimage/generate_signing_key
--- a/signimage/generate_signing_key
+++ b/signimage/generate_signing_key
@@ -11,12 +11,13 @@
 # support such "read" calls (Busybox 1.24.2 knows the needed options), specify the    #
 # password as argument during call.                                                   #
 #                                                                                     #
-# We assume enough entropy here ... please make sure there's enough                   #
-# randomness, before you call this script and you should be profoundly                #
-# convinced, that your "openssl" binary does not seed the PRNG with any               #
-# fixed value. You could read some values from /dev/random (not /dev/urandom, because #
-# this uses unblocking access and may return poor values, if no entropy is available) #
-# before you call this script.                                                        #
+# We assume enough entropy here ... please make sure there's enough randomness,       #
+# before you call this script and you should be profoundly  convinced, that your      #
+# "openssl" binary does not seed the PRNG with any fixed value.                       #
+#                                                                                     # 
+# You could read some values from /dev/random (not /dev/urandom, because this uses    #
+# unblocking access and may return poor values, if no entropy is available)  before   #
+# you call this script.                                                               #
 #                                                                                     #
 # $ dd if=/dev/random bs=1 count=16 status=none | busybox hd                          #
 # 00000000  8f 29 47 29 4a b7 95 de  b0 f5 75 52 6c 51 63 4f  |.)G)J.....uRlQcO|      #
@@ -55,7 +56,7 @@ show_version()
 	local v
 	v=$(openssl version 2>/dev/null)
 	if [ $? -eq 127 ]; then
-		echo "Missing 'openssl' binary." 1>&2
+		echo -e "Missing \x1B[1mopenssl\x1B[0m binary." 1>&2
 		return 1
 	else
 		echo -e "Found \x1B[1;34m$v\x1B[0m" 1>&2
@@ -99,7 +100,7 @@ show_version
 if [ $? -eq 127 ]; then
 	exit 1
 fi
-echo -n "Check 'genrsa' command ... " 1>&2
+echo -en "Check \x1B[1mgenrsa\x1B[0m command ... " 1>&2
 openssl genrsa -dummy 2>&1 | grep -q '^usage: genrsa' 2>/dev/null 1>&2
 rc=$?
 if [ $rc -eq 0 ]; then
@@ -134,7 +135,7 @@ else
 	if [ "$KEYSIZE" == "1024" -o "$KEYSIZE" == "2048" -o "$KEYSIZE" == "4096" ]; then
 		key_size=$KEYSIZE
 	else
-		echo "Unsupported key size '$KEYSIZE' found in the environment." 1>&2
+		echo "Unsupported key size \x1B[1m$KEYSIZE\x1B[0m found in the environment." 1>&2
 		exit 1
 	fi
 fi
diff --git a/signimage/sign_image b/signimage/sign_image
--- a/signimage/sign_image
+++ b/signimage/sign_image
@@ -27,6 +27,7 @@
 my_path="$0"
 [ "${my_path%/*}" == "$my_path" ] && my_path="." || my_path="${my_path%/*}"
 my_name="${0##*/}"
+box_key_name="/var/flash/websrv_ssl_key"
 ####################################################################################
 #                                                                                  #
 # include the common file definitions                                              #
@@ -45,7 +46,7 @@ show_version()
 	local v
 	v=$(openssl version 2>/dev/null)
 	if [ $? -eq 127 ]; then
-		echo "Missing 'openssl' binary." 1>&2
+		echo -e "Missing \x1B[1mopenssl\x1B[0m binary." 1>&2
 		return 1
 	else
 		echo -e "Found \x1B[1;34m$v\x1B[0m" 1>&2
@@ -74,7 +75,36 @@ usage()
 VM implementation. If you know for sure, that you will only use non-\nAVM scripts/c\
 omponents to sign and verify, you may specify a better\nhash algorithm (remember th\
 at the openssl binary still has to support\nit) with an environment variable USEHAS\
-H specifying the name of the\nalgorithm to use."
+H specifying the name of the\nalgorithm to use.\n"
+	echo -e "A special use case is the signing of a TAR file directly in a FRITZ!OS\
+\nenvironment, if such a signature is surely checked later only on the\nsame device\
+. Than we may use the RSA key from \x1B[1mwebsrv_ssl_key.pem\x1B[0m\ninstead of an \
+additional key and we don't need to specify its\npassword, because it may be read w\
+ith  \x1B[1mprivatekeypassword \x1B[0m. To switch\nthis script into this 'internal-\
+only mode', set the environment\nvariable SIGN_ON_BOX to '1' while calling it. Be a\
+ware, that a key\nsize other than 1024 bits would lead to the impossibility to veri\
+fy\nthe signed file with AVM components."
+}
+####################################################################################
+#                                                                                  #
+# try to identify FRITZ!OS as runtime environment (not too sophisticated, but it   #
+# should be able to make this distinction)                                         #
+#                                                                                  #
+####################################################################################
+is_fritzos_environment()
+{
+	local rc=1 eva_prompt="Eva_AVM"
+	[ ${#HWRevision} -eq 0 ] && return $rc
+	[ ${#CONFIG_ENVIRONMENT_PATH} -eq 0 ] && return $rc
+	[ -d "$CONFIG_ENVIRONMENT_PATH" ] || return $rc
+	[ -f "$CONFIG_ENVIRONMENT_PATH/environment" ] || return $rc
+	local HWRev="$(sed -n -e "s|^HWRevision\t\(.*\)\$|\1|p" $CONFIG_ENVIRONMENT_PATH/environment)"
+	[ ${#HWRev} -eq 0 ] && return $rc
+	[ "$HWRev" != "$HWRevision" ] && return $rc
+	local prompt="$(sed -n -e "s|^prompt\t\(.*\)\$|\1|p" $CONFIG_ENVIRONMENT_PATH/environment)"
+	[ ${#prompt} -eq 0 ] && return $rc
+	[ "$prompt" != "$eva_prompt" ] && return $rc
+	return 0
 }
 ####################################################################################
 #                                                                                  #
@@ -88,7 +118,7 @@ else
 	image_file="$1"
 fi
 if ! [ -f "$image_file" ]; then
-	echo "The specified image file \x1B[1m]$image_file\x1B[0m] does not exist." 1>&2
+	echo -e "The specified image file \x1B[1m$image_file\x1B[0m does not exist." 1>&2
 	exit 1
 fi
 ####################################################################################
@@ -98,7 +128,7 @@ fi
 ####################################################################################
 show_version
 [ $? -ne 0 ] && exit 1
-echo -n "Check 'dgst' command ... " 1>&2
+echo -en "Check \x1B[1mdgst\x1B[0m command ... " 1>&2
 echo "" | openssl dgst 2>&1 | grep -q '^(stdin)=' 2>/dev/null 1>&2
 rc=$?
 if [ $rc -eq 0 ]; then
@@ -107,7 +137,7 @@ else
 	show_error
 	exit 1
 fi
-echo -n "Check 'rsa' command ... " 1>&2
+echo -en "Check  \x1B[1mrsa \x1B[0m command ... " 1>&2
 echo "" | openssl rsa 2>&1 | grep -q '^unable to load' 2>/dev/null 1>&2
 rc=$?
 if [ $rc -eq 0 ]; then
@@ -131,13 +161,13 @@ if [ "${#USEHASH}" -gt 0 ]; then
 		fi
 	done
 	if [ "${#hash_algo}" -eq 0 ]; then
-		echo "Unknown or unsupported (by this script) hash algorithm '$USEHASH' specified."
+		echo -e "Unknown or unsupported (by this script) hash algorithm \x1B[1m$USEHASH\x1B[0m specified." 1>&2
 		exit 1
 	fi
 else
 	hash_algo="md5"
 fi
-echo -n "Verify hash algorithm '$hash_algo' is supported ... " 1>&2
+echo -en "Verify hash algorithm  \x1B[1m$hash_algo \x1B[0m is supported ... " 1>&2
 echo "" | openssl dgst -$hash_algo 2>&1 2>/dev/null 1>&2
 rc=$?
 if [ $rc -eq 0 ]; then
@@ -153,12 +183,12 @@ fi
 ####################################################################################
 dd if="$image_file" bs=1 skip=257 count=5 status=none 2>/dev/null | grep -q "^ustar\$" 2>/dev/null
 if [ $? -ne 0 ]; then
-	echo "Input file doesn't look like a TAR archive." 1>&2
+	echo -e "Input file doesn't look like a TAR archive." 1>&2
 	exit 1
 fi
 dd if="$image_file" bs=100 count=1 status=none 2>/dev/null | grep -q "PaxHeaders" 2>/dev/null
 if [ $? -eq 0 ]; then
-	echo "Input file contains extended headers (PaxHeaders) and may not be signed this way." 1>&2
+	echo -e "Input file contains extended headers (PaxHeaders) and may not be signed this way." 1>&2
 	exit 1
 fi
 ####################################################################################
@@ -191,7 +221,7 @@ while read line; do
 	eval $line
 	copy_blocks=$(( copy_blocks + BLOCKS ))
 	if [ "$MEMBER" == "./var/signature" ]; then
-		echo "The input file already contains a member './var/signature' and may not be signed (again) by this script." 1>&2
+		echo -e "The input file already contains a member \x1B[1m./var/signature\x1B[0m and may not be signed (again) by this script." 1>&2
 		exit 1
 	fi
 done <"$tmp/image_members"
@@ -199,38 +229,73 @@ file_size="$(stat -c %s "$image_file")"
 file_blocks=$(( file_size / 512 ))
 eoa_blocks=$(( file_blocks - copy_blocks ))
 if [ $eoa_blocks -gt 4 ]; then
-	echo "The end of archive markers at the input file are too large: blocks expected=4, blocks present=$eoa_blocks." 1>&2
-	echo "The input file will be truncated after the last archive member." 1>&2
+	echo -e "The end of archive markers at the input file are too large: blocks expected=\x1B[1m4\x1B[0m, blocks present=\x1B[1m$eoa_blocks\x1B[0m." 1>&2
+	echo -e "The input file will be truncated after the last archive member." 1>&2
 fi
 ####################################################################################
 #                                                                                  #
-# get the password for the private key                                             #
+# check the special case of signing on the FRITZ!Box with the internal key         #
 #                                                                                  #
 ####################################################################################
-if [ -z $2 ]; then
-	if ! [ -t 0 ]; then
-		usage 1>&2
-		exit 1
+on_box=0
+if [ ${#SIGN_ON_BOX} -gt 0 ]; then
+	if [ "$SIGN_ON_BOX" == "1" ]; then
+		if ! is_fritzos_environment; then
+			echo -e "The special mode to sign an image with the FRITZ!OS RSA key may only be used in a FRITZ!OS environment."
+			exit 1
+		else
+			pkp="$(which privatekeypassword)"
+			found=$rc
+			if [ $found -ne 0 ]; then
+				echo -e "The \x1B[1mprivatekeypassword\x1B[0m executable is missing." 1>&2
+				exit 1
+			else
+				KEYPASSWORD="$(privatekeypassword 2>/dev/null)"
+				if [ ${#KEYPASSWORD} -eq 0 ]; then
+					echo -e "Error determining the password for the FRITZ!OS RSA key." 1>&2
+					exit 1
+				else
+					name_prefix="$box_key_name"
+					private_extension="pem"
+					on_box=1
+				fi
+			fi
+		fi
+	fi		
+fi
+####################################################################################
+#                                                                                  #
+# get the password for the private key, if needed                                  #
+#                                                                                  #
+####################################################################################
+if [ $on_box -eq 0 ]; then
+	if [ -z $2 ]; then
+		if ! [ -t 0 ]; then
+			usage 1>&2
+			exit 1
+		else
+			read -sp "Enter the password for the signing key: " KEYPASSWORD
+			echo "" 1>&2
+		fi
 	else
-		read -sp "Enter the password for the signing key: " KEYPASSWORD
-		echo "" 1>&2
+		KEYPASSWORD="$2"
 	fi
-else
-	KEYPASSWORD="$2"
 fi
 ####################################################################################
 #                                                                                  #
 # check key password first (and key file presence)                                 #
 #                                                                                  #
 ####################################################################################
-echo -en "Check the password for the private key file ... " 1>&2
-openssl rsa -in "${name_prefix}.${private_extension}" -noout -passin "pass:$KEYPASSWORD" 2>/dev/null 1>&2
-rc=$?
-if [ $rc -eq 0 ]; then
-	show_ok 
-else
-	show_error
-	exit 1
+if [ $on_box -eq 0 ]; then
+	echo -en "Check the password for the private key file ... " 1>&2
+	openssl rsa -in "${name_prefix}.${private_extension}" -noout -passin "pass:$KEYPASSWORD" 2>/dev/null 1>&2
+	rc=$?
+	if [ $rc -eq 0 ]; then
+		show_ok 
+	else
+		show_error
+		exit 1
+	fi
 fi
 ####################################################################################
 #                                                                                  #
@@ -264,7 +329,7 @@ dd if=/dev/zero of="$tmp/1K.bin" bs=512 count=2 status=none 2>/dev/null
 # - an additional 1K block of zeroes serves as new EoA header                      #
 #                                                                                  #
 ##################################A#################################################
-echo -en "Signing the image hash ($hash_algo) with RSA key from \x1B[1m${name_prefix}.${private_extension}\x1B[0m ... " 1>&2
+echo -en "Signing the image hash (\x1B[1m$hash_algo\x1B[0m) with RSA key from \x1B[1m${name_prefix}.${private_extension}\x1B[0m ... " 1>&2
 dd if="$image_file" bs=512 count=$copy_blocks status=none 2>&1 | cat - "$tmp/1K.bin" "$tmp/1K.bin" | 
 openssl dgst -$hash_algo -sign "${name_prefix}.${private_extension}" -out "$tmp/var/signature" -passin "pass:$KEYPASSWORD"
 rc=$?
@@ -286,7 +351,7 @@ dd if="$image_file" bs=512 count=$copy_blocks status=none
 # and append another TAR archive containing only our newly created signature file  #
 #                                                                                  #
 ####################################################################################
-tar --version | grep -q GNU 2>/dev/null && format=" --format=gnu" || format=""
+tar --version 2>/dev/null | grep -q GNU 2>/dev/null && format=" --format=gnu" || format=""
 tar $format -C "$tmp" -O -c ./var/signature | dd bs=512 count=4 status=none 2>/dev/null
 show_ok
 ####################################################################################
@@ -300,4 +365,3 @@ exit 0
 # end of file                                                                      #
 #                                                                                  #
 ####################################################################################
-
