extend the usable key sizes
- you may use RSA keys of 1024, 2048 and 4096 bits to sign
  and verify own images
- in conjunction with better hash algorithms this should
  be safe for the next years again
- keep in mind, that the original firmware by AVM isn't
  able to handle larger keys or other digests yet, you
  can use these options only, if the verification is done
  by the scripts found here (or in another implementation
  supporting this)
- the limitation to max. 4096 bits in the key ensures,
  that the resulting ./var/signature in the signed archive
  file still fits into a single 512-byte block, which
  avoids additional changes to the archive handling code

diff --git a/signimage/generate_signing_key b/signimage/generate_signing_key
--- a/signimage/generate_signing_key
+++ b/signimage/generate_signing_key
@@ -14,8 +14,8 @@
 # We assume enough entropy here ... please make sure there's enough                   #
 # randomness, before you call this script and you should be profoundly                #
 # convinced, that your "openssl" binary does not seed the PRNG with any               #
-# fixed value. You could read some values from /dev/random (not                       #
-# /dev/urandom, because this is unblocking and may return poor values),               #
+# fixed value. You could read some values from /dev/random (not /dev/urandom, because #
+# this uses unblocking access and may return poor values, if no entropy is available) #
 # before you call this script.                                                        #
 #                                                                                     #
 # $ dd if=/dev/random bs=1 count=16 status=none | busybox hd                          #
@@ -72,7 +72,14 @@ usage()
 	echo -e "\x1B[1mCreate a RSA key pair to sign image files for AVM routers.\x1B[0m\n"
 	echo -e "Usage:\n"
 	echo -e "$0 [\x1B[1mpassword\x1B[0m]\n"
-	echo -e "The \x1B[1mpassword\x1B[0m will be read from the terminal, if it's not specified."
+	echo -e "The \x1B[1mpassword\x1B[0m will be read from the terminal, if it's not specified.\n"
+	echo -e "The script may generate a key with more than 1024 bit length, if the environment"
+	echo -e "variable KEYSIZE is set to the requested length, but \x1B[1m1024\x1B[0m, \x1B[1m\
+2048\x1B[0m and \x1B[1m4096\x1B[0m are the"
+	echo -e "only valid selections, because larger keys would affect the size of the encrypted"
+	echo -e "signature file and this would need further changes. Please keep in mind, that you"
+	echo -e "cannot use such a key with the original AVM code (yet - I hope, they will change"
+	echo -e "something in the near future, to re-establish a secure handling of images)."
 }
 #######################################################################################
 #                                                                                     #
@@ -118,6 +125,21 @@ else
 fi
 #######################################################################################
 #                                                                                     #
+# set or check the key size to generate                                               #
+#                                                                                     #
+#######################################################################################
+if [ ${#KEYSIZE} -eq 0 ]; then
+	key_size=1024
+else
+	if [ "$KEYSIZE" == "1024" -o "$KEYSIZE" == "2048" -o "$KEYSIZE" == "4096" ]; then
+		key_size=$KEYSIZE
+	else
+		echo "Unsupported key size '$KEYSIZE' found in the environment." 1>&2
+		exit 1
+	fi
+fi
+#######################################################################################
+#                                                                                     #
 # generate a random seed file with content from /dev/random, it will be used later to #
 # call "openssl genrsa"                                                               #
 #                                                                                     #
@@ -139,7 +161,7 @@ fi
 #                                                                                     #
 #######################################################################################
 echo -en "Generating RSA key as \x1B[1m${name_prefix}.${private_extension}\x1B[0m ... " 1>&2
-KEYPASSWORD="${KEYPASSWORD}" openssl genrsa -aes128 -passout env:KEYPASSWORD -out "${name_prefix}.${private_extension}" -rand "${name_prefix}.${seed_extension}" -f4 1024 2>/dev/null
+KEYPASSWORD="${KEYPASSWORD}" openssl genrsa -aes128 -passout env:KEYPASSWORD -out "${name_prefix}.${private_extension}" -rand "${name_prefix}.${seed_extension}" -f4 $key_size 2>/dev/null
 rc=$?
 if [ $rc -ne 0 -o ! -f "${name_prefix}.${private_extension}" ]; then
 	show_error
@@ -188,9 +210,15 @@ fi
 # show some additional info                                                           #
 #                                                                                     #
 #######################################################################################
-echo -en "\nYou should copy the file \x1B[1m${name_prefix}.${avm_extension}\x1B[0m to \
-your firmware image as \x1B[1m/etc/avm_firmware_public_key9\x1B[0m to use it for image \
-verification with AVM components.\n" | fold -w 80 -s 1>&2
+if [ $key_size -eq 1024 ]; then
+	echo -en "\nYou should copy the file \x1B[1m${name_prefix}.${avm_extension}\x1B[0m \
+to your firmware image as \x1B[1m/etc/avm_firmware_public_key9\x1B[0m to use it for ima\
+ge verification with AVM components.\n" | fold -w 80 -s 1>&2
+else
+	echo -en "\nThe generated key may be used to sign own TAR archives, if they will be\
+ checked later without AVM components. The used key size of $key_size bits isn't suppor\
+ted yet by the original firmware.\n" | fold -w 80 -s 1>&2
+fi
 #######################################################################################
 #                                                                                     #
 # all done                                                                            #
