I've found a better display solution in the internal 'sign_image' script and changed this one here to use the same include file as the other scripts.

diff --git a/signimage/generate_signing_key b/signimage/generate_signing_key
--- a/signimage/generate_signing_key
+++ b/signimage/generate_signing_key
@@ -1,46 +1,113 @@
 #! /bin/sh
-#
-# generate a RSA key usable to sign a firmware image, which may pass the signature
-# checks in current FRITZ!OS versions and convert the public key to a file, which
-# may be included into an own image for later use
-#
-# This script needs a full-functioning OpenSSL binary ('genrsa' is embedded into 
-# FRITZ!OS images, but 'rsa' and 'rsautl' are not available) and a shell version,
-# which may use "read -sp" for hidden terminal reads. If your shell does not 
-# support such "read" calls (Busybox 1.24.2 knows the needed options), specify the 
-# password as argument during call.
-#
-# We assume enough entropy here ... please make sure there's enough
-# randomness, before you call this script and you should be profoundly
-# convinced, that your "openssl" binary does not seed the PRNG with any
-# fixed value. You should read some values from /dev/random (not
-# /dev/urandom, because this is unblocking and may return poor values),
-# before you call this script.
-# 
-# $ dd if=/dev/random bs=1 count=16 status=none | busybox hd
-# 00000000  8f 29 47 29 4a b7 95 de  b0 f5 75 52 6c 51 63 4f  |.)G)J.....uRlQcO|
-# 00000010
-#
-# Afterwards the call to 'genrsa' may take some more time, but it should
-# get really random values for the key generation. 
-#
-# You may also generate your own random seed file (default name is 
-# image_signing.rnd) to seed the PRNG for the 'genrsa' call. If this file is
-# missing, it will be created with 16x16 bytes from /dev/random (time consuming).
-#
-# The files are generated with fixed names in the current directory.
-#
-# file name definitions for output files are imported from "include file"
-. image_signing.inc
-#
-# check or get a password for the new key
-#
+#######################################################################################
+#                                                                                     #
+# generate a RSA key usable to sign a firmware image, which may pass the signature    #
+# checks in current FRITZ!OS versions and convert the public key to a file, which     #
+# may be included into an own image for later use                                     #
+#                                                                                     #
+# This script needs a full-functioning OpenSSL binary ('genrsa' is embedded into      #
+# FRITZ!OS images, but 'rsa' and 'rsautl' are not available) and a shell version,     #
+# which may use "read -sp" for hidden terminal reads. If your shell does not          #
+# support such "read" calls (Busybox 1.24.2 knows the needed options), specify the    #
+# password as argument during call.                                                   #
+#                                                                                     #
+# We assume enough entropy here ... please make sure there's enough                   #
+# randomness, before you call this script and you should be profoundly                #
+# convinced, that your "openssl" binary does not seed the PRNG with any               #
+# fixed value. You could read some values from /dev/random (not                       #
+# /dev/urandom, because this is unblocking and may return poor values),               #
+# before you call this script.                                                        #
+#                                                                                     #
+# $ dd if=/dev/random bs=1 count=16 status=none | busybox hd                          #
+# 00000000  8f 29 47 29 4a b7 95 de  b0 f5 75 52 6c 51 63 4f  |.)G)J.....uRlQcO|      #
+# 00000010                                                                            #
+#                                                                                     #
+# Afterwards the call to 'genrsa' may take some more time, but it should              #
+# get really random values for the key generation.                                    #
+#                                                                                     #
+# You may also generate your own random seed file (have a look at the file name       #
+# definitions in the include file for further explanations) to seed the PRNG for      #
+# the 'genrsa' call.                                                                  #
+#                                                                                     #
+#######################################################################################
+#                                                                                     #
+# determine our script path to locate the include file                                #
+#                                                                                     #
+#######################################################################################
+my_path="$0"
+[ "${my_path%/*}" == "$my_path" ] && my_path="." || my_path="${my_path%/*}"
+my_name="${0##*/}"
+#######################################################################################
+#                                                                                     #
+# include the common file definitions                                                 #
+#                                                                                     #
+#######################################################################################
+source "$my_path/image_signing_files.inc"
+#######################################################################################
+#                                                                                     #
+# some subfunctions                                                                   #
+#                                                                                     #
+#######################################################################################
+show_error() { echo -e "\x1B[1;31mFAILED\x1B[0m" 1>&2; }
+show_ok() { echo -e "\x1B[1;32mOK\x1B[0m" 1>&2; }
+show_version()
+{
+	local v
+	v=$(openssl version 2>/dev/null)
+	if [ $? -eq 127 ]; then
+		echo "Missing 'openssl' binary." 1>&2
+		return 1
+	else
+		echo -e "Found \x1B[1;34m$v\x1B[0m" 1>&2
+		return 0
+	fi
+}
+#######################################################################################
+#                                                                                     #
+# usage screen, caller has to redirect output to STDERR if needed                     #
+#                                                                                     #
+#######################################################################################
+usage()
+{
+	echo -e "\x1B[1mCreate a RSA key pair to sign image files for AVM routers.\x1B[0m\n"
+	echo -e "Usage:\n"
+	echo -e "$0 [\x1B[1mpassword\x1B[0m]\n"
+	echo -e "The \x1B[1mpassword\x1B[0m will be read from the terminal, if it's not specified."
+}
+#######################################################################################
+#                                                                                     #
+# check parameters                                                                    #
+#                                                                                     #
+#######################################################################################
+if [ x"$1" == x"-h" -o x"$1" == x"--help" ]; then
+	usage 1>&2
+	exit 1
+fi
+#######################################################################################
+#                                                                                     #
+# check OpenSSL presence and version                                                  #
+#                                                                                     #
+#######################################################################################
+show_version
+if [ $? -eq 127 ]; then
+	exit 1
+fi
+echo -n "Check 'genrsa' command ... " 1>&2
+openssl genrsa -dummy 2>&1 | grep -q '^usage: genrsa' 2>/dev/null 1>&2
+rc=$?
+if [ $rc -eq 0 ]; then
+	show_ok
+else
+	show_error
+fi
+#######################################################################################
+#                                                                                     #
+# get and check the password for the new key                                          #
+#                                                                                     #
+#######################################################################################
 if [ -z $1 ]; then
 	if ! [ -t 0 ]; then
-		echo "Usage: $0 <password>" 1>&2
-		echo "Create a 1024 bit RSA key usable to sign image files for AVM routers." 1>&2
-		echo "If no password is specified on the command line, it will be read from" 1>&2
-		echo "the terminal." 1>&2
+		usage 1>&2
 		exit 1
 	else
 		read -sp "Enter a password for the generated key: " KEYPASSWORD
@@ -49,83 +116,89 @@ if [ -z $1 ]; then
 else
 	KEYPASSWORD="$1"
 fi
-#
-# check OpenSSL presence and version
-#
-version="$(openssl version)"
-if [ $? -eq 127 ]; then
-	echo "Missing 'openssl' binary." 1>&2
-	exit 1
-fi
-echo "Found $version" 1>&2
-echo -n "Check 'genrsa' command ... " 1>&2
-openssl genrsa -dummy 2>&1 | grep -q '^usage: genrsa' 2>/dev/null 1>&2
-rc=$?
-if [ $rc -eq 0 ]; then
-	echo "OK" 1>&2
-else
-	echo "FAILED" 1>&2
-fi
-#
-# generate a random seed file with content from /dev/random, it will be used later to
-# call "openssl genrsa"
-#
+#######################################################################################
+#                                                                                     #
+# generate a random seed file with content from /dev/random, it will be used later to #
+# call "openssl genrsa"                                                               #
+#                                                                                     #
+#######################################################################################
 if ! [ -f "${name_prefix}.${seed_extension}" ]; then
 	echo -n "Generating random seed file from /dev/random (may take some time) ... " 1>&2
 	dd if=/dev/random of="${name_prefix}.${seed_extension}" bs=16 count=16 status=none 2>/dev/null
 	if [ $rc -ne 0 -o ! -f "${name_prefix}.${seed_extension}" ]; then
-		echo "FAILED" 1>&2
+		show_error
+		exit 1
 	else
-		echo "OK" 1>&2
+		show_ok
 	fi
 fi
-#
-# generate the RSA key first, we need a 1024 bit key (even today and even
-# if such keys are considered unsafe this time)
-#
-echo -n "Generating RSA key as '${name_prefix}.${private_extension}' ... " 1>&2
+#######################################################################################
+#                                                                                     #
+# generate the RSA key first, we need a 1024 bit key (even today and even if such     #
+# keys are considered unsafe this time)                                               #
+#                                                                                     #
+#######################################################################################
+echo -en "Generating RSA key as \x1B[1m${name_prefix}.${private_extension}\x1B[0m ... " 1>&2
 KEYPASSWORD="${KEYPASSWORD}" openssl genrsa -aes128 -passout env:KEYPASSWORD -out "${name_prefix}.${private_extension}" -rand "${name_prefix}.${seed_extension}" -f4 1024 2>/dev/null
 rc=$?
 if [ $rc -ne 0 -o ! -f "${name_prefix}.${private_extension}" ]; then
-	echo "FAILED" 1>&2
+	show_error
+	exit 1
 else
-	echo "OK" 1>&2
+	show_ok
 fi
-#
-# extract public key as PEM file
-#
-echo -n "Extracting public key to '${name_prefix}.${public_extension}' ... " 1>&2
+#######################################################################################
+#                                                                                     #
+# extract public key as PEM file                                                      #
+#                                                                                     #
+#######################################################################################
+echo -en "Extracting public key to \x1B[1m${name_prefix}.${public_extension}\x1B[0m ... " 1>&2
 KEYPASSWORD="${KEYPASSWORD}" openssl rsa -passin env:KEYPASSWORD -pubout -out "${name_prefix}.${public_extension}" -in "${name_prefix}.${private_extension}" 2>/dev/null
 rc=$?
 if [ $rc -ne 0 -o ! -f "${name_prefix}.${public_extension}" ]; then
-	echo "FAILED" 1>&2
+	show_error
+	exit 1
 else
-	echo "OK" 1>&2
+	show_ok
 fi
-#
-# extract modulus and exponent to create the AVM formatted public key
-#
-echo -n "Extracting public key in AVM format to '${name_prefix}.${avm_extension}' ... " 1>&2
-# the exponent was set by '-f4' and does not need to be read from file
+#######################################################################################
+#                                                                                     #
+# extract modulus and exponent to create the AVM formatted public key                 #
+# - the exponent was set by '-f4' and does not need to be read from file              #
+# - the modulus has to start without highest bit set (to ensure positive number)      # 
+#                                                                                     #
+#######################################################################################
+echo -en "Extracting public key in AVM format to \x1B[1m${name_prefix}.${avm_extension}\x1B[0m ... " 1>&2
 EXPONENT=010001
 eval $(openssl rsa -in "${name_prefix}.${public_extension}" -pubin -modulus -noout)
 rc=$?
 if [ $rc -ne 0 ]; then
-	echo "FAILED" 1>&2
+	show_error
+	exit 1
 else
 	MODULUS="$(echo "$Modulus" | tr 'A-F' 'a-f')"
 	first=${MODULUS:0:1}
-	# start without highest bit set (to ensure positive number)
 	[ "${first/[89a-f]/}" != "$first" ] && MODULUS="00$MODULUS"
 	echo $MODULUS >"${name_prefix}.${avm_extension}"
 	echo $EXPONENT >>"${name_prefix}.${avm_extension}"
-	echo "OK" 1>&2
+	show_ok
 fi
-#
-# show some additional info
-#
-echo "" 1>&2
-echo "You should copy the file '${name_prefix}.${avm_extension}' to your firmware image" 1>&2
-echo "as '/etc/avm_firmware_public_key9' to use it for image verification" 1>&2
-echo "with AVM components." 1>&2
+#######################################################################################
+#                                                                                     #
+# show some additional info                                                           #
+#                                                                                     #
+#######################################################################################
+echo -en "\nYou should copy the file \x1B[1m${name_prefix}.${avm_extension}\x1B[0m to \
+your firmware image as \x1B[1m/etc/avm_firmware_public_key9\x1B[0m to use it for image \
+verification with AVM components.\n" | fold -w 80 -s 1>&2
+#######################################################################################
+#                                                                                     #
+# all done                                                                            #
+#                                                                                     #
+#######################################################################################
 exit 0
+#######################################################################################
+#                                                                                     #
+# end of file                                                                         #
+#                                                                                     #
+#######################################################################################
