sometime C&P even duplicates our mistakes

diff --git a/signimage/generate_signing_key b/signimage/generate_signing_key
--- a/signimage/generate_signing_key
+++ b/signimage/generate_signing_key
@@ -30,86 +30,88 @@
 #
 # The files are generated with fixed names in the current directory.
 #
-# file name definitions for output files
-name_prefix="image_signing"
-private_extension="key"
-public_extension="pem"
-avm_extension="asc"
-seed_extension="rnd"
+# file name definitions for output files are imported from "include file"
+. image_signing.inc
+#
+# check or get a password for the new key
 #
 if [ -z $1 ]; then
 	if ! [ -t 0 ]; then
-		echo "Usage: $0 <password>" 2>&1
-		echo "Create a 1024 bit RSA key usable to sign image files for AVM routers." 2>&1
-		echo "If no password is specified on the command line, it will be read from" 2>&1
-		echo "the terminal." 2>&1
+		echo "Usage: $0 <password>" 1>&2
+		echo "Create a 1024 bit RSA key usable to sign image files for AVM routers." 1>&2
+		echo "If no password is specified on the command line, it will be read from" 1>&2
+		echo "the terminal." 1>&2
 		exit 1
 	else
 		read -sp "Enter a password for the generated key: " KEYPASSWORD
-		echo ""
+		echo "" 1>&2
 	fi
 else
-	export KEYPASSWORD="$1"
+	KEYPASSWORD="$1"
 fi
 #
 # check OpenSSL presence and version
 #
 version="$(openssl version)"
 if [ $? -eq 127 ]; then
-	echo "Missing 'openssl' binary." 2>&1
+	echo "Missing 'openssl' binary." 1>&2
 	exit 1
 fi
-echo "Found $version" 2>&1
-echo -n "Check 'genrsa' command ... " 2>&1
+echo "Found $version" 1>&2
+echo -n "Check 'genrsa' command ... " 1>&2
 openssl genrsa -dummy 2>&1 | grep -q '^usage: genrsa' 2>/dev/null 1>&2
 rc=$?
-[ $rc -eq 0 ] && echo "OK" || "echo FAILED"
+if [ $rc -eq 0 ]; then
+	echo "OK" 1>&2
+else
+	echo "FAILED" 1>&2
+fi
 #
 # generate a random seed file with content from /dev/random, it will be used later to
 # call "openssl genrsa"
 #
 if ! [ -f "${name_prefix}.${seed_extension}" ]; then
-	echo -n "Generating random seed file from /dev/random (may take some time) ... " 2>&1
+	echo -n "Generating random seed file from /dev/random (may take some time) ... " 1>&2
 	dd if=/dev/random of="${name_prefix}.${seed_extension}" bs=16 count=16 status=none 2>/dev/null
 	if [ $rc -ne 0 -o ! -f "${name_prefix}.${seed_extension}" ]; then
-		echo "FAILED" 2>&1
+		echo "FAILED" 1>&2
 	else
-		echo "OK" 2>&1
+		echo "OK" 1>&2
 	fi
 fi
 #
 # generate the RSA key first, we need a 1024 bit key (even today and even
 # if such keys are considered unsafe this time)
 #
-echo -n "Generating RSA key as '${name_prefix}.${private_extension}' ... " 2>&1
+echo -n "Generating RSA key as '${name_prefix}.${private_extension}' ... " 1>&2
 KEYPASSWORD="${KEYPASSWORD}" openssl genrsa -aes128 -passout env:KEYPASSWORD -out "${name_prefix}.${private_extension}" -rand "${name_prefix}.${seed_extension}" -f4 1024 2>/dev/null
 rc=$?
 if [ $rc -ne 0 -o ! -f "${name_prefix}.${private_extension}" ]; then
-	echo "FAILED" 2>&1
+	echo "FAILED" 1>&2
 else
-	echo "OK" 2>&1
+	echo "OK" 1>&2
 fi
 #
 # extract public key as PEM file
 #
-echo -n "Extracting public key to '${name_prefix}.${public_extension}' ... " 2>&1
+echo -n "Extracting public key to '${name_prefix}.${public_extension}' ... " 1>&2
 KEYPASSWORD="${KEYPASSWORD}" openssl rsa -passin env:KEYPASSWORD -pubout -out "${name_prefix}.${public_extension}" -in "${name_prefix}.${private_extension}" 2>/dev/null
 rc=$?
 if [ $rc -ne 0 -o ! -f "${name_prefix}.${public_extension}" ]; then
-	echo "FAILED" 2>&1
+	echo "FAILED" 1>&2
 else
-	echo "OK" 2>&1
+	echo "OK" 1>&2
 fi
 #
 # extract modulus and exponent to create the AVM formatted public key
 #
-echo -n "Extracting public key in AVM format to '${name_prefix}.${avm_extension}' ... " 2>&1
+echo -n "Extracting public key in AVM format to '${name_prefix}.${avm_extension}' ... " 1>&2
 # the exponent was set by '-f4' and does not need to be read from file
 EXPONENT=010001
 eval $(openssl rsa -in "${name_prefix}.${public_extension}" -pubin -modulus -noout)
 rc=$?
 if [ $rc -ne 0 ]; then
-	echo "FAILED" 2>&1
+	echo "FAILED" 1>&2
 else
 	MODULUS="$(echo "$Modulus" | tr 'A-F' 'a-f')"
 	first=${MODULUS:0:1}
@@ -117,13 +119,13 @@ else
 	[ "${first/[89a-f]/}" != "$first" ] && MODULUS="00$MODULUS"
 	echo $MODULUS >"${name_prefix}.${avm_extension}"
 	echo $EXPONENT >>"${name_prefix}.${avm_extension}"
-	echo "OK" 2>&1
+	echo "OK" 1>&2
 fi
 #
 # show some additional info
 #
-echo ""
-echo "You should copy the file '${name_prefix}.${avm_extension}' to your firmware image" 2>&1
-echo "as '/etc/avm_firmware_public_key9' to use it for image verification" 2>&1
-echo "with AVM components." 2>&1
+echo "" 1>&2
+echo "You should copy the file '${name_prefix}.${avm_extension}' to your firmware image" 1>&2
+echo "as '/etc/avm_firmware_public_key9' to use it for image verification" 1>&2
+echo "with AVM components." 1>&2
 exit 0
