signimage: enhanced POSIX compatibility with ShellCheck

diff --git a/signimage/sign_image b/signimage/sign_image
--- a/signimage/sign_image
+++ b/signimage/sign_image
@@ -27,6 +27,7 @@
 ####################################################################################
 my_path="$0"
 [ "${my_path%/*}" = "$my_path" ] && my_path="." || my_path="${my_path%/*}"
+# shellcheck disable=SC2034
 my_name="${0##*/}"
 box_key_name="/var/flash/websrv_ssl_key"
 signature_file="./var/signature"
@@ -45,31 +46,31 @@ signature_file="./var/signature"
 # substitution, but spreading 'eval' statements all over the code looks ugly, too  #
 #                                                                                  #
 ####################################################################################
-if ! [ -z "$YF_SIGNIMAGE_TAR" ]; then
+if [ -n "$YF_SIGNIMAGE_TAR" ]; then
 	__YF_SIGNIMAGE_TAR="$YF_SIGNIMAGE_TAR"
 	__yf_signimage_tar()
 	{
-		eval $__YF_SIGNIMAGE_TAR $*
+		"$__YF_SIGNIMAGE_TAR" "$@"
 	}
 	YF_SIGNIMAGE_TAR="__yf_signimage_tar"
 else
 	YF_SIGNIMAGE_TAR="tar"
 fi
-if ! [ -z "$YF_SIGNIMAGE_DD" ]; then
+if [ -n "$YF_SIGNIMAGE_DD" ]; then
 	__YF_SIGNIMAGE_DD="$YF_SIGNIMAGE_DD"
 	__yf_signimage_dd()
 	{
-		eval $__YF_SIGNIMAGE_DD $*
+		"$__YF_SIGNIMAGE_DD" "$@"
 	}
 	YF_SIGNIMAGE_DD="__yf_signimage_dd"
 else
 	YF_SIGNIMAGE_DD="dd"
 fi
-if ! [ -z "$YF_SIGNIMAGE_OPENSSL" ]; then
+if [ -n "$YF_SIGNIMAGE_OPENSSL" ]; then
 	__YF_SIGNIMAGE_OPENSSL="$YF_SIGNIMAGE_OPENSSL"
 	__yf_signimage_openssl()
 	{
-		eval $__YF_SIGNIMAGE_OPENSSL $*
+		"$__YF_SIGNIMAGE_OPENSSL" "$@"
 	}
 	YF_SIGNIMAGE_OPENSSL="__yf_signimage_openssl"
 else
@@ -84,22 +85,21 @@ show_error() ( printf "\033[1;31mFAILED\033[0m\a\n" 1>&2; )
 show_ok() ( printf "\033[1;32mOK\033[0m\n" 1>&2; )
 show_version()
 (
-	local v
 	v=$("$YF_SIGNIMAGE_OPENSSL" version 2>/dev/null)
 	if [ $? -eq 127 ]; then
 		printf "\033[1;31mMissing \033[1;37mopenssl\033[1;31m binary, set \033[1;37mYF_SIGNIMAGE_OPENSSL\033[1;31m variable to its path name.\033[0m\a\n" 1>&2
-		return 1
+		exit 1
 	else
-		printf "Found \033[1;34m$v\033[0m\n" 1>&2
-		return 0
+		printf "Found \033[1;34m%s\033[0m\n" "$v" 1>&2
+		exit 0
 	fi
 )
 __check_required_command()
 (
 	IFS=:
-	set -- $1
-	for n in $@; do
-		command -v $n 2>/dev/null 1>&2 && exit 0
+	set -- "$1"
+	for n in "$@"; do
+		command -v "$n" 2>/dev/null 1>&2 && exit 0
 	done
 	exit 1
 )
@@ -124,7 +124,7 @@ __random()
 __mktmp()
 (
 	if __check_required_command "mktemp"; then
-		n="$(mktemp $* 2>/dev/null)"
+		n="$(mktemp "$@" 2>/dev/null)"
 	fi
 	if [ -z "$n" ]; then
 		t="${TMPDIR:-/tmp}"
@@ -142,11 +142,12 @@ __mktmp()
 			touch "$n" 2>/dev/null
 		fi
 	fi
-	printf "$n"
+	printf "%s\n" "$n"
 )
 __read_password()
 (
-	printf "$1" 1>&2
+	printf "%s" "$1" 1>&2
+	# shellcheck disable=SC2162
 	read password
 	# printf "\n" 1>&2
 	printf "%s\n" "$password"
@@ -160,7 +161,7 @@ usage()
 (
 	printf "\033[1mSign a tar archive file as firmware image for FRITZ!OS devices.\033[0m\n\n"
 	printf "Usage:\n\n"
-	printf "$0 \033[1mimagefile\033[0m [\033[1mpassword\033[0m]\n\n"
+	printf "%s \033[1mimagefile\033[0m [\033[1mpassword\033[0m]\n\n" "$0"
 	printf "\033[1mimagefile\033[0m is the archive to sign, there must be no \033[1mvar/signature\033[0m file\n"
 	printf "embedded yet.\n\n"
 	printf "The \033[1mpassword\033[0m will be read from the terminal, if it's not specified.\n"
@@ -190,10 +191,11 @@ checksum()
 (
 	read_values()
 	{
+		# shellcheck disable=SC2162,SC2034
 		while read pos left right; do
 			sum=$(( sum + 0$left ))
 		done
-		printf "%d" $sum
+		printf "%d" "$sum"
 	}
 	sum=0
 	cmp -l -- "$1" /dev/zero 2>/dev/null | read_values
@@ -207,11 +209,12 @@ checksum()
 is_fritzos_environment()
 (
 	eva_prompt="Eva_AVM"
+	# shellcheck disable=SC2154
 	[ ${#HWRevision} -eq 0 ] && exit 1
 	[ ${#CONFIG_ENVIRONMENT_PATH} -eq 0 ] && exit 1
 	[ -d "$CONFIG_ENVIRONMENT_PATH" ] || exit 1
 	[ -f "$CONFIG_ENVIRONMENT_PATH/environment" ] || exit 1
-	HWRev="$(sed -n -e "s|^HWRevision\t\(.*\)\$|\1|p" $CONFIG_ENVIRONMENT_PATH/environment)"
+	HWRev="$(sed -n -e "s|^HWRevision\t\(.*\)\$|\1|p" "$CONFIG_ENVIRONMENT_PATH/environment")"
 	[ ${#HWRev} -eq 0 ] && exit 1
 	if [ "$HWRev" != "$HWRevision" ]; then
 		if [ -z "$YF_SIGNIMAGE_IGNORE_HWREVISION" ]; then
@@ -220,7 +223,7 @@ is_fritzos_environment()
 		fi
 		printf "\033[1;37mHWRevision\033[1;33m mismatch between shell and urlader environment (\033[1;37m%s\033[1;33m vs. \033[1;37m%s\033[1;33m) ignored.\033[0m\n" "$HWRev" "$HWRevision" 1>&2
 	fi
-	prompt="$(sed -n -e "s|^prompt\t\(.*\)\$|\1|p" $CONFIG_ENVIRONMENT_PATH/environment)"
+	prompt="$(sed -n -e "s|^prompt\t\(.*\)\$|\1|p" "$CONFIG_ENVIRONMENT_PATH/environment")"
 	[ ${#prompt} -eq 0 ] && exit 1
 	[ "$prompt" != "$eva_prompt" ] && exit 1
 	exit 0
@@ -249,8 +252,7 @@ fi
 # check OpenSSL presence and version                                               #
 #                                                                                  #
 ####################################################################################
-show_version
-[ $? -ne 0 ] && exit 1
+show_version || exit 1
 printf "Check \033[1mdgst\033[0m command ... " 1>&2
 printf "" | "$YF_SIGNIMAGE_OPENSSL" dgst 2>&1 | grep -q '^(stdin)=' 2>/dev/null 1>&2
 rc=$?
@@ -285,13 +287,13 @@ if [ "${#USEHASH}" -gt 0 ]; then
 		fi
 	done
 	if [ "${#hash_algo}" -eq 0 ]; then
-		printf "\033[1;31mUnknown or unsupported (by this script) hash algorithm \033[1;37m$USEHASH\033[1;31m specified.\033[0m\a\n" 1>&2
+		printf "\033[1;31mUnknown or unsupported (by this script) hash algorithm \033[1;37m%s\033[1;31m specified.\033[0m\a\n" "$USEHASH" 1>&2
 		exit 1
 	fi
 else
 	hash_algo="md5"
 fi
-printf "Verify hash algorithm \033[1m$hash_algo\033[0m is supported ... " 1>&2
+printf "Verify hash algorithm \033[1m%s\033[0m is supported ... " "$hash_algo" 1>&2
 printf "" | "$YF_SIGNIMAGE_OPENSSL" dgst -$hash_algo 2>&1 2>/dev/null 1>&2
 rc=$?
 if [ $rc -eq 0 ]; then
@@ -305,82 +307,10 @@ fi
 # use 'force-local' option with GNU TAR, if the image name contains a colon        #
 #                                                                                  #
 ####################################################################################
-if [ -n "$(expr "$image_file" : ".*\(:\).*")" ]; then
-	"$YF_SIGNIMAGE_TAR" --help 2>&1 | grep -q 'force-local' 2>/dev/null && force_local="--force-local"
-else
-	force_local=""
-fi
-####################################################################################
-#                                                                                  #
-# verify input file format                                                         #
-#                                                                                  #
-####################################################################################
-printf "Checking input file format ... " 1>&2
-"$YF_SIGNIMAGE_DD" if="$image_file" bs=1 skip=257 count=5 status=none 2>/dev/null | grep -q "^ustar\$" 2>/dev/null
-if [ $? -ne 0 ]; then
-	show_error
-	printf "\033[1;31mInput file doesn't look like a TAR archive.\033[0m\a\n" 1>&2
-	exit 1
-fi
-"$YF_SIGNIMAGE_DD" if="$image_file" bs=100 count=1 status=none 2>/dev/null | grep -q "PaxHeaders" 2>/dev/null
-if [ $? -eq 0 ]; then
-	show_error
-	printf "\033[1;31mInput file contains extended headers (PaxHeaders) and may not be signed this way.\033[0m\a\n" 1>&2
-	exit 1
-fi
-####################################################################################
-#                                                                                  #
-# check first archive member (name=./var/, type=directory)                         #
-#                                                                                  #
-####################################################################################
-if ! [ "$("$YF_SIGNIMAGE_DD" if="$image_file" bs=1 count=7 2>/dev/null | base64)" = "Li92YXIvAA==" ] || \
-   ! [ "$("$YF_SIGNIMAGE_DD" if="$image_file" bs=1 count=1 skip=156 2>/dev/null)" = "5" ]; then
-	show_error
-	printf "\033[1;31mFirst member of archive file has to be a directory and has to use the name '\033[1;37m./var/\033[1;31m'.\033[0m\a\n" 1>&2
-	exit 1
-fi
-####################################################################################
-#                                                                                  #
-# prepare a temporary directory and cleanup on exit                                #
-#                                                                                  #
-####################################################################################
-tmp=$(__mktmp -d)
-[ $? -eq 127 ] && tmp="/tmp/tmp.$(date +%s).$$" && mkdir -p "$tmp"
-trap "rm -r \"$tmp\"" EXIT HUP
-####################################################################################
-#                                                                                  #
-# check end of archive headers, GNU tar writes more than needed                    #
-#                                                                                  #
-####################################################################################
-offset=0
-"$YF_SIGNIMAGE_TAR" -t -v -f "$image_file" $force_local |
-sed -n -e "s|^[^ ]* *[^ ]* *\([0-9]*\) *[^ ]* *[^ ]* *\(.*\)\$|SIZE=\1 MEMBER=\"\2\"|p" |
-while read line; do
-	eval $line
-	file_offset="$offset"
-	file_start="$(( file_offset + 512 ))"
-	file_end="$(( file_start + SIZE ))"
-	offset="$(( ( ( file_end + 511 ) / 512 ) * 512 ))"
-	printf "HEADER=%u START=%u END=%u SIZE=%u BLOCKS=%u MEMBER=\"%s\"\n" "$file_offset" "$file_start" "$file_end" "$SIZE" "$(( ( offset - file_offset ) / 512 ))" "$MEMBER" >>"$tmp/image_members"
-done
-copy_blocks=0
-while read line; do
-	i=$(( i + 1 ))
-	eval $line
-	copy_blocks="$(( copy_blocks + BLOCKS ))"
-	if [ "$MEMBER" = "$signature_file" ]; then
-		show_error
-		printf "\033[1;31mThe input file already contains a member '\033[1;37m%s\033[1;31m' and may not be signed (again) by this script.\033[0m\a\n" "$signature_file" 1>&2
-		exit 1
-	fi
-done <"$tmp/image_members"
-file_size="$(cat "$image_file" | wc -c)"
-file_blocks=$(( file_size / 512 ))
-eoa_blocks=$(( file_blocks - copy_blocks ))
-show_ok
-if [ $eoa_blocks -gt 2 ]; then
-	printf "\033[1;33mThe end of archive markers at the input file are too large\033[0m: blocks expected=\033[1m%u\033[0m, blocks present=\033[1m%u\033[0m.\n\033[1;33mThe input file will be truncated after the last archive member.\033[0m\n" "2" "$eoa_blocks" 1>&2
-fi
+unset force_local
+[ -n "$(expr "$image_file" : ".*\(:\).*")" ] && \
+"$YF_SIGNIMAGE_TAR" --help 2>&1 | grep -q 'force-local' 2>/dev/null && \
+force_local="--force-local"
 ####################################################################################
 #                                                                                  #
 # check the special case of signing on the FRITZ!Box with the internal key         #
@@ -409,6 +339,77 @@ if [ ${#SIGN_ON_BOX} -gt 0 ]; then
 			fi
 		fi
 	fi
+fi
+####################################################################################
+#                                                                                  #
+# verify input file format                                                         #
+#                                                                                  #
+####################################################################################
+printf "Checking input file format ... " 1>&2
+if ! "$YF_SIGNIMAGE_DD" if="$image_file" bs=1 skip=257 count=5 status=none 2>/dev/null | grep -q "^ustar\$" 2>/dev/null; then
+	show_error
+	printf "\033[1;31mInput file doesn't look like a TAR archive.\033[0m\a\n" 1>&2
+	exit 1
+fi
+if "$YF_SIGNIMAGE_DD" if="$image_file" bs=100 count=1 status=none 2>/dev/null | grep -q "PaxHeaders" 2>/dev/null; then
+	show_error
+	printf "\033[1;31mInput file contains extended headers (PaxHeaders) and may not be signed this way.\033[0m\a\n" 1>&2
+	exit 1
+fi
+####################################################################################
+#                                                                                  #
+# check first archive member (name=./var/, type=directory)                         #
+#                                                                                  #
+####################################################################################
+if ! [ "$("$YF_SIGNIMAGE_DD" if="$image_file" bs=1 count=7 2>/dev/null | base64)" = "Li92YXIvAA==" ] || \
+   ! [ "$("$YF_SIGNIMAGE_DD" if="$image_file" bs=1 count=1 skip=156 2>/dev/null)" = "5" ]; then
+	show_error
+	printf "\033[1;31mFirst member of archive file has to be a directory and has to use the name '\033[1;37m./var/\033[1;31m'.\033[0m\a\n" 1>&2
+	exit 1
+fi
+####################################################################################
+#                                                                                  #
+# prepare a temporary directory and cleanup on exit                                #
+#                                                                                  #
+####################################################################################
+tmp=$(__mktmp -d)
+[ $? -eq 127 ] && tmp="/tmp/tmp.$(date +%s).$$" && mkdir -p "$tmp"
+trap 'rm -r \"$tmp\" 2>/dev/null 1>&2' EXIT HUP
+####################################################################################
+#                                                                                  #
+# check end of archive headers, GNU tar writes more than needed                    #
+#                                                                                  #
+####################################################################################
+offset=0
+# shellcheck disable=SC2162
+"$YF_SIGNIMAGE_TAR" -t -v -f "$image_file" $force_local | \
+sed -n -e "s|^[^ ]* *[^ ]* *\([0-9]*\) *[^ ]* *[^ ]* *\(.*\)\$|SIZE=\1 MEMBER=\"\2\"|p" | \
+while read line; do
+	eval "$line"
+	file_offset="$offset"
+	file_start="$(( file_offset + 512 ))"
+	file_end="$(( file_start + SIZE ))"
+	offset="$(( ( ( file_end + 511 ) / 512 ) * 512 ))"
+	printf "HEADER=%u START=%u END=%u SIZE=%u BLOCKS=%u MEMBER=\"%s\"\n" "$file_offset" "$file_start" "$file_end" "$SIZE" "$(( ( offset - file_offset ) / 512 ))" "$MEMBER" >>"$tmp/image_members"
+done
+copy_blocks=0
+# shellcheck disable=SC2162
+while read line; do
+	i=$(( i + 1 ))
+	eval "$line"
+	copy_blocks="$(( copy_blocks + BLOCKS ))"
+	if [ "$MEMBER" = "$signature_file" ]; then
+		show_error
+		printf "\033[1;31mThe input file already contains a member '\033[1;37m%s\033[1;31m' and may not be signed (again) by this script.\033[0m\a\n" "$signature_file" 1>&2
+		exit 1
+	fi
+done <"$tmp/image_members"
+file_size="$(wc -c < "$image_file")"
+file_blocks=$(( file_size / 512 ))
+eoa_blocks=$(( file_blocks - copy_blocks ))
+show_ok
+if [ $eoa_blocks -gt 2 ]; then
+	printf "\033[1;33mToo much end of archive markers read from input file:\033[0m blocks expected=\033[1m%u\033[0m, blocks present=\033[1m%u\033[0m.\n\033[1;33mInput data will be truncated after last archive member.\033[0m\n" "2" "$eoa_blocks" 1>&2
 fi
 ####################################################################################
 #                                                                                  #
@@ -491,13 +492,11 @@ fi
 # - an additional 1K block of zeros serves as new EoA header                       #
 #                                                                                  #
 ##################################A#################################################
-printf "Signing the image hash (\033[1m$hash_algo\033[0m) with RSA key from \033[1m${name_prefix}.${private_extension}\033[0m ... " 1>&2
-"$YF_SIGNIMAGE_DD" if="$image_file" bs=512 count=$copy_blocks status=none 2>&1 | cat - "$tmp/filler.bin" "$tmp/1K.bin" "$tmp/1K.bin" |
-"$YF_SIGNIMAGE_OPENSSL" dgst -$hash_algo -sign "${name_prefix}.${private_extension}" -out "$tmp/$signature_file" -passin "pass:$KEYPASSWORD"
-rc=$?
-if [ $rc -eq 0 ]; then
+printf "Signing the image hash (\033[1m$hash_algo\033[0m) with RSA key from \033[1m%s.%s\033[0m ... " "$name_prefix" "$private_extension" 1>&2
+if "$YF_SIGNIMAGE_DD" if="$image_file" bs=512 count=$copy_blocks status=none 2>&1 | cat - "$tmp/filler.bin" "$tmp/1K.bin" "$tmp/1K.bin" | \
+"$YF_SIGNIMAGE_OPENSSL" dgst -$hash_algo -sign "${name_prefix}.${private_extension}" -out "$tmp/$signature_file" -passin "pass:$KEYPASSWORD"; then
 	show_ok
-	sigsize="$(cat "$tmp/$signature_file" | wc -c)"
+	sigsize="$(wc -c < "$tmp/$signature_file")"
 else
 	show_error
 	exit 1
@@ -517,11 +516,11 @@ cat "$tmp/filler.bin"
 ####################################################################################
 "$YF_SIGNIMAGE_DD" if="$image_file" of="$tmp/header" bs=512 count=1 status=none 2>/dev/null
 printf "%s" "${signature_file##*/}" | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=6 conv=notrunc status=none 2>/dev/null
-printf "%04o\000" $sigsize | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=131 conv=notrunc status=none 2>/dev/null
+printf "%04o\000" "$sigsize" | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=131 conv=notrunc status=none 2>/dev/null
 printf "0" | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=156 conv=notrunc status=none 2>/dev/null
 printf "        " | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=148 conv=notrunc status=none 2>/dev/null
 chksum=$(checksum "$tmp/header")
-printf "%06o\000" $chksum  | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=148 conv=notrunc status=none 2>/dev/null
+printf "%06o\000" "$chksum" | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=148 conv=notrunc status=none 2>/dev/null
 ####################################################################################
 #                                                                                  #
 # and append signature content and EoA blocks                                      #
