signimage: add modulus from environment variable as an option

diff --git a/signimage/yf_check_signature b/signimage/yf_check_signature
--- a/signimage/yf_check_signature
+++ b/signimage/yf_check_signature
@@ -301,6 +301,8 @@ usage()
 	printf    "              isn't the default 0x010001), SRC (optional) as a pseudo filename and DESC (optional,\n"
 	printf    "              too) as a description to be displayed for this key (the DESC value is unused yet)\n\n"
 	printf -- "-a \033[1mfilename\033[0m - add key from specified file (AVM's text format) to the list\n\n"
+	printf -- "-e \033[1mvariable\033[0m - add modulus from specified environment variable (hexadecimal string) with a fixed\n"
+	printf    "              exponent of 0x010001\n\n"
 	printf -- "-p \033[1mfilename\033[0m - add key from specified file (PEM format) to the list\n\n"
 	printf -- "-d \033[1mfilename\033[0m - add key from specified file (DER format) to the list\n\n"
 	printf -- "-s          - verify that image file was signed with RSA key from local FRITZ!OS device (script is\n"
@@ -858,6 +860,26 @@ while [ "$#" -gt 0 ]; do
 			fi
 			shift
 			;;
+		"-e")
+			if [ -z "$2" ]; then
+				printf "\033[1;31mMissing variable name after \033[1;37m-e\033[1;31m option.\033[0m\a\n" 1>&2
+				exit $YF_CHECK_SIGNATURE_MISSING_ARGUMENTS
+			fi
+			unset MOD
+			unset EXP
+			MOD="$(env | sed -n -e "s|^$2=\(.*\)|\1|p")"
+			EXP=010001
+			if [ ${#MOD} -gt 0 ]; then
+				if ! check_modulus "$MOD"; then
+					printf "\033[1;33mInvalid modulus value on line 1 of file \033[1;37m%s\033[1;33m.\033[0m\n" "$2" 1>&2
+					exit $YF_CHECK_SIGNATURE_INVALID_DATA
+				fi
+				printf "DESC=\"environment variable from command line\" SRC=\"%s\" MOD=%s EXP=%s\n" "$2" "$MOD" "$EXP" >>"$tmp/$public_keys_list"
+			else
+				printf "\033[1;33mThe specified environment variable \033[1;37m%s\033[1;33m is missing or has an empty value.\033[0m\a\n" "$2" 1>&2
+			fi
+			shift 2
+			;;
 		*)
 			printf "\033[1;31mUnknown option \033[1;37m%s\033[1;31m specified on command line.\033[0m\a\n" "$1" 1>&2
 			exit $YF_CHECK_SIGNATURE_INVALID_OPTION
@@ -873,6 +895,7 @@ fi
 # find the public key corresponding to the private key, which was used to sign the image              #
 #                                                                                                     #
 #######################################################################################################
+[ "$YF_CHECK_SIGNATURE_SHOW_KEYS" = "1" ] && { printf "\n=== public keys collected ===\n" && cat "$tmp/$public_keys_list" && printf "=============================\n\n"; } 1>&2
 [ "$(wc -l <"$tmp/$public_keys_list")" -gt 1 ] && printf "Trying to determine the correct key now ...\n" 1>&2
 key_found=0
 # shellcheck disable=SC2162
