signimage: updated script versions with better ...
handling of interruptions (e.g. Ctrl-C aka SIGINT) and removal of
intermediate results.

Also file info headers and some comments were added in preparation
of publishing these scripts on GitHub.

diff --git a/signimage/database/extract_filesystems b/signimage/database/extract_filesystems
--- a/signimage/database/extract_filesystems
+++ b/signimage/database/extract_filesystems
@@ -1,31 +1,82 @@
 #! /bin/bash
-srcdir="$1"
+#######################################################################################################
+#                                                                                                     #
+# extract SquashFS image files from firmware images                                                   #
+#                                                                                                     #
+###################################################################################################VER#
+#                                                                                                     #
+# extract_filesystems, version 0.6                                                                    #
+#                                                                                                     #
+# This script is a part of the YourFritz project from https://github.com/PeterPawn/YourFritz.         #
+#                                                                                                     #
+###################################################################################################CPY#
+#                                                                                                     #
+# Copyright (C) 2017-2019 P.Haemmerlein (peterpawn@yourfritz.de)                                      #
+#                                                                                                     #
+###################################################################################################LIC#
+#                                                                                                     #
+# This project is free software, you can redistribute it and/or modify it under the terms of the GNU  #
+# General Public License as published by the Free Software Foundation; either version 2 of the        #
+# License, or (at your option) any later version.                                                     #
+#                                                                                                     #
+# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without   #
+# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      #
+# General Public License under http://www.gnu.org/licenses/gpl-2.0.html for more details.             #
+#                                                                                                     #
+#######################################################################################################
+#                                                                                                     #
+# Run the script without parameters for an usage description.                                         #
+#                                                                                                     #
+#######################################################################################################
+usage()
+(
+	printf "Extract SquashFS images from a firmware image in TAR archive format.\n\n"
+	printf "Copyright (C) 2017-2019 P. Haemmerlein (peterpawn@yourfritz.de)\n\n"
+	printf "Usage:\n\n"
+	printf "\033[1m%s\033[0m <local_directory> <handler_script> [ parameter ]\n\n" "${0##*/}"
+	printf "All firmware image files in the specified directory are processed in the\n"
+	printf "order of a 'find' command. If the image contains a combined file with\n"
+	printf "kernel and filesystem (the contained file 'filesystem.image' has a zero\n"
+	printf "length in this case), this one gets extracted instead of the usual file\n"
+	printf "'filesystem.image'.\n\n"
+	printf "After the file was extracted successfully, the specified command is called\n"
+	printf "for further processing.\n\n"
+	printf "The extracted filesystem image is temporarily stored in the processed source\n"
+	printf "directory, therefore this directory has to be writable by the caller.\n"
+)
 
-( [ -z "$srcdir" ] || ! [ -d "$srcdir" ] ) &&  exit 1
+[ -z "$1" ] && usage && exit 0
+
+srcdir="$1"
+handler="$2"
+shift 2
+
+( [ -z "$srcdir" ] || ! [ -d "$srcdir" ] || [ -z "$handler" ] || ! [ -x "$handler" ] ) && usage 1>&2 && exit 1
+
+trap "rm -f "$srcdir/tar_list" "$src_dir/filesystem" 2>/dev/null" HUP EXIT INT
 
 rm "$srcdir/tar_list" 2>/dev/null
 mkfifo "$srcdir/tar_list"
 
-for f in $(find "$srcdir" -type f -name "*.image"); do
-	tar --list --verbose --file=$f --wildcards ./var/tmp/\*.image &>"$srcdir/tar_list" &
+[ "$(set -o 2>/dev/null | sed -n -e 's|^xtrace[ \t]*\(.*\)$|\1|p')" = "on" ] && xtrace="-x " || xtrace=""
+
+for image in $(find "$srcdir" -type f -name "*.image"); do
+	tar --list --verbose --file="$image" --wildcards ./var/tmp/\*.image > "$srcdir/tar_list" 2>&1 &
 	while read line; do
 		filename="$(expr "$line" : ".* \./var/tmp/\([^ ]*\)")"
 		filesize="$(expr "$line" : "[^ \t]*[ \t]*[^ \t]*[ \t]*\([^ \t]*\)[ \t].*")"
 		if [ "$filename" = "filesystem.image" ]; then
-			if [ "$filesize" -ne 0 ]; then
-				tar --extract --file=$f --to-stdout ./var/tmp/filesystem.image >"$srcdir/filesystem"
-				printf ">>> %s\n" "$f" 1>&2
-				[ "$(set -o 2>/dev/null | sed -n -e 's|^xtrace[ \t]*\(.*\)$|\1|p')" = "on" ] && xtrace="-x " || xtrace=""
-				/proc/self/exe $xtrace process_filesystem "$srcdir/filesystem"
-				break
-			else
-				tar --extract --file=$f --to-stdout ./var/tmp/kernel.image >"$srcdir/filesystem"
-				printf ">>> %s\n" "$f" 1>&2
-				/proc/self/exe $xtrace process_filesystem "$srcdir/filesystem"
-			fi
+			[ "$filesize" -eq 0 ] && filename="kernel" || filename="filesystem"
+			tar --extract --file="$image" --to-stdout ./var/tmp/${filename}.image > "$srcdir/filesystem"
+			/proc/self/exe $xtrace "$handler" "$srcdir/filesystem" $* "$image"
+			rm "$srcdir/filesystem" 2>/dev/null
+			break
 		fi
-	done <"$srcdir/tar_list"
+	done < "$srcdir/tar_list"
 done
-
-rm "$srcdir/tar_list" "$srcdir/filesystem" 2>/dev/null
-
+#######################################################################################################
+#                                                                                                     #
+# end of script, cleanup will be done by a trap                                                       #
+#                                                                                                     #
+#######################################################################################################
+exit 0
diff --git a/signimage/database/get_pinned_key b/signimage/database/get_pinned_key
--- a/signimage/database/get_pinned_key
+++ b/signimage/database/get_pinned_key
@@ -1,22 +1,102 @@
 #! /bin/bash
-[ -z "$1" ] && printf "\033[1mCall this script with the DNS name of a HTTPS server as parameter.\033[0m\n" && exit 1
+#######################################################################################################
+#                                                                                                     #
+# prepare a pinned public key for mass-download of firmware files from server of vendor.              #
+#                                                                                                     #
+###################################################################################################VER#
+#                                                                                                     #
+# get_pinned_key, version 0.6                                                                         #
+#                                                                                                     #
+# This script is a part of the YourFritz project from https://github.com/PeterPawn/YourFritz.         #
+#                                                                                                     #
+###################################################################################################CPY#
+#                                                                                                     #
+# Copyright (C) 2017-2019 P.Haemmerlein (peterpawn@yourfritz.de)                                      #
+#                                                                                                     #
+###################################################################################################LIC#
+#                                                                                                     #
+# This project is free software, you can redistribute it and/or modify it under the terms of the GNU  #
+# General Public License as published by the Free Software Foundation; either version 2 of the        #
+# License, or (at your option) any later version.                                                     #
+#                                                                                                     #
+# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without   #
+# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      #
+# General Public License under http://www.gnu.org/licenses/gpl-2.0.html for more details.             #
+#                                                                                                     #
+#######################################################################################################
+#                                                                                                     #
+# Run the script without parameters for an usage description.                                         #
+#                                                                                                     #
+#######################################################################################################
+usage()
+(
+	printf "Prepare a pinned public key for mass-download from server of vendor.\n\n"
+	printf "Copyright (C) 2017-2019 P. Haemmerlein (peterpawn@yourfritz.de)\n\n"
+	printf "Usage:\n\n"
+	printf "\033[1m%s\033[0m <url>\n\n" "${0##*/}"
+	printf "The certificate of the specified server will be downloaded and - if the\n"
+	printf "chain was successfully verified - displayed for a manual verification,\n"
+	printf "that the certificate was issued for the expected server and purpose.\n\n"
+	printf "If the certificate passes all checks, its public key  gets stored in a\n"
+	printf "local file '<servername>.pem' and may be used as pinned key for further\n"
+	printf "TLS connections to this server.\n"
+)
+
+[ -z "$1" ] && usage 1>&2 && exit 1
+
 server="$1"
-printf "\033[1mPlease verify the certificate chain shown for the TLS certificate from '\033[1;93m%s\033[1;37m' carefully, before its public key gets used as pinned public key for further 'wget' downloads.\033[0m\n\n" "$server"
-echo | openssl s_client -connect "$server":443 | openssl x509 -outform pem -pubkey -noout -out "$server.pem.new"
+tmp="${TMPDIR:-/tmp}"
+
+trap "rm "$tmp/ssl_connection" "$tmp/ssl_certificate" "$server.pem.new" 2>/dev/null" EXIT HUP INT
+
+export LC_CTYPE="en_US.UTF-8"
+printf "\n" | openssl s_client -tls1_2 -connect "$server":443 > "$tmp/ssl_connection" 2>&1
 [ $? -ne 0 ] && printf "\033[1;91mError accessing server at '\033[1;93m%s\033[1;91m:443'.\033[0m\n" "$server" && exit 1
-printf "\n\033[1mContinue only, if the certificate chain was successfully verified and the presented certificate is for the right domain.\033[0m\n"
+
+verification="$(grep "^Verification" "$tmp/ssl_connection")"
+if [ "$verification" = "Verification: OK" ]; then
+	sed -n -e "/BEGIN CERTIFICATE/,/END CERTIFICATE/p" "$tmp/ssl_connection" > "$tmp/ssl_certificate"
+	rm "$tmp/ssl_connection" 2>/dev/null
+	openssl x509 -outform pem -pubkey -noout -out "$server.pem.new" -in "$tmp/ssl_certificate"
+else
+	printf "\033[1mThe certificate chain could not be verified.\033[0m\n\n"
+	exit 1
+fi
+
+printf "\033[1mPlease verify the certificate chain shown for the TLS certificate from\n\n"
+printf "\033[1;93m%s\033[1;37m\n\n" "$server"
+printf "carefully, before its public key gets used as pinned public key for further 'wget' downloads.\033[0m\n\n"
+	openssl x509 -noout -text -in "$tmp/ssl_certificate"
+
+
+printf "\n\033[1mContinue only, if the certificate chain was successfully verified and the presented\n"
+printf "certificate is for the right domain.\033[0m\n\n"
+
 while [ 0 -eq 0 ]; do
 	printf "\033[1;37mContinue? (enter '\033[1;93myes\033[1;37m' or '\033[1;93mno\033[1;37m') \033[1;94m"
 	read answer
 	[ "$answer" = "yes" ] && break
 	[ "$answer" = "no" ] && break
 done
+
+rm "$tmp/ssl_connection" 2>/dev/null
+
 if [ "$answer" = "no" ]; then
 	rm -f "$server.pem.new"
 	printf "\033[1;91mDownloaded public key for '\033[1;93m%s\033[1;91m' was NOT saved.\033[0m\n" "$server"
 	exit 1
 fi
+
 mv "$server.pem.new" "$server.pem"
-printf "\033[1;37mDownloaded public key from '\033[1;93m%s\033[1;37m' was stored as '\033[1;93m%s\033[1;37m'.\033[0m\n" "$server" "$server.pem"
-printf "\033[1;37mIt may be used now to ensure the identity of the server, while downloading firmware files from this source.\033[0m\n"
+
+printf "\033[1;37mDownloaded public key from\n\n"
+printf "\033[1;93m%s\033[1;37m\n\n" "$server"
+printf "was stored as '\033[1;93m%s\033[1;37m'.\033[0m\n\n" "$server.pem"
+printf "\033[1;37mIt may be used now to ensure the identity of the server, while downloading firmware\n"
+printf "files from this source.\033[0m\n"
+#######################################################################################################
+#                                                                                                     #
+# end of script                                                                                       #
+#                                                                                                     #
+#######################################################################################################
 exit 0
diff --git a/signimage/database/process_filesystem b/signimage/database/process_filesystem
--- a/signimage/database/process_filesystem
+++ b/signimage/database/process_filesystem
@@ -1,5 +1,78 @@
 #! /bin/bash
+#######################################################################################################
+#                                                                                                     #
+# extract all files from a SquashFS image                                                             #
+#                                                                                                     #
+###################################################################################################VER#
+#                                                                                                     #
+# process_filesystem, version 0.6                                                                     #
+#                                                                                                     #
+# This script is a part of the YourFritz project from https://github.com/PeterPawn/YourFritz.         #
+#                                                                                                     #
+###################################################################################################CPY#
+#                                                                                                     #
+# Copyright (C) 2017-2019 P.Haemmerlein (peterpawn@yourfritz.de)                                      #
+#                                                                                                     #
+###################################################################################################LIC#
+#                                                                                                     #
+# This project is free software, you can redistribute it and/or modify it under the terms of the GNU  #
+# General Public License as published by the Free Software Foundation; either version 2 of the        #
+# License, or (at your option) any later version.                                                     #
+#                                                                                                     #
+# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without   #
+# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      #
+# General Public License under http://www.gnu.org/licenses/gpl-2.0.html for more details.             #
+#                                                                                                     #
+#######################################################################################################
+#                                                                                                     #
+# Run the script without parameters for an usage description.                                         #
+#                                                                                                     #
+#######################################################################################################
+usage()
+(
+	printf "Extract files from SquashFS images.\n\n"
+	printf "Copyright (C) 2017-2019 P. Haemmerlein (peterpawn@yourfritz.de)\n\n"
+	printf "Usage:\n\n"
+	printf "\033[1m%s\033[0m <squashfs_image> <handler_script> [ parameters ]\n\n" "${0##*/}"
+	printf "This script extracts the all files from the specified SquashFS image into\n"
+	printf "a temporary directory and calls the specified handler script with the\n"
+	printf "name of this directory as first parameter. The called script decides,\n"
+	printf "which further actions will be taken. The directory is removed immediately,\n"
+	printf "if control is returned to this script.\n\n"
+	printf "The input image gets removed, if this script itself exits, but even before,\n"
+	printf "the input file is seen as 'volatile' and it gets removed or replaced, if\n"
+	printf "necessary to extract any embedded SquashFS image as core filesystems.\n"
+	printf "Therefore the directory with the input image has to be writable by the\n"
+	printf "caller.\n\n"
+	printf "The temporary directory used for extraction is created below the path,\n"
+	printf "which is specified by the environment value 'TMPDIR', or below '/tmp', if\n"
+	printf "the value is missing.\n"
+)
+
 fs="$1"
+handler="$2"
+shift 2
+tmp="${TMPDIR:-/tmp}"
+
+( [ -z "$handler" ] || ! [ -f "$fs" ] || ! [ -x "$handler" ] ) && usage 1>&2 && exit 1
+
+cleanup()
+{
+	[ -d "img" ] || return
+	if grep -q "$(realpath "img")" /proc/mounts 2>/dev/null; then
+		dev="$(sed -n -e "s|\([^ \t]*\) $(realpath "img") .*|\1|p" /proc/mounts)"
+		[ -n "$dev" ] && umount "$dev" 2>/dev/null
+	fi
+	if grep -q "$fs.img" /sys/devices/virtual/block/loop*/loop/backing_file 2>/dev/null; then
+		losetup -d "/dev/$(grep -l "filesystem.img" /sys/devices/virtual/block/loop*/loop/backing_file 2>/dev/null | sed -n -e "1s|/sys/devices/virtual/block/\(loop[0-9]*\)/loop.*|\1|p")"
+	fi
+	rmdir "img" 2>/dev/null
+}
+
+trap "cleanup; rm -r "${tmp}/process_filesystem" "$fs" "$fs.img" 2>/dev/null" HUP EXIT INT
+
+[ "$(set -o 2>/dev/null | sed -n -e 's|^xtrace[ \t]*\(.*\)$|\1|p')" = "on" ] && xtrace="-x " || xtrace=""
+
 type="$(file "$fs")"
 if [ -n "$(expr "$type" : ".*\(Squashfs filesystem\).*")" ]; then
 	version="$(expr "$type" : ".*version \([0-9]\.0\).*")"
@@ -8,10 +81,12 @@ if [ -n "$(expr "$type" : ".*\(Squashfs filesystem\).*")" ]; then
 		rm "$fs.img" 2>/dev/null
 		mv "$fs" "$fs.img" 2>/dev/null
 		if [ "$version" = "0.0" ]; then
+			# it's an ext2 filesystem with the dummy header, mount it somewhere to extract the core filesystem
 			loop="$(losetup --offset 256 --find --read-only --show "$fs.img" 2>/dev/null)"
 			if expr "$loop" : "/dev/loop.*" >/dev/null 2>/dev/null; then
 				mkdir img 2>/dev/null
 				mount -o ro "$loop" "./img"
+				exit
 				cp "img/filesystem_core.squashfs" "$fs"
 				umount "$loop"
 				losetup -d "$loop" 2>/dev/null
@@ -19,6 +94,7 @@ if [ -n "$(expr "$type" : ".*\(Squashfs filesystem\).*")" ]; then
 				rm "$fs.img" 2>/dev/null
 			fi
 		else
+			# it's an old SquashFS3 filesystem, use 'unsquashfs' as usual, but extract only the core filesystem
 			endianess="$(expr "$type" : ".*, \(big\|little\) endian,.*")"
 			[ "$endianess" = "big" ] && endianess="be" || endianess="le"
 			unsquashfs4-$endianess "$fs.img" "filesystem_core.squashfs" 2>/dev/null 1>&2
@@ -27,11 +103,12 @@ if [ -n "$(expr "$type" : ".*\(Squashfs filesystem\).*")" ]; then
 			rm -r ./squashfs-root 2>/dev/null
 		fi
 		type="$(file "$fs")"
-		[ -z "$(expr "$type" : ".*\(Squashfs filesystem\).*")" ] && exit 1
+		[ -z "$(expr "$type" : ".*\(Squashfs filesystem\).*")" ] && rm "$fs.img" "$fs" 2>/dev/null && exit 1
 	fi
 	[ -n "$(expr "$type" : ".*\(big endian\).*")" ] && endianess=be || endianess=le
 	stat="$(./unsquashfs4-$endianess -stat -k "$fs" 2>&1)"
 elif [ -n "$(expr "$type" : ".*\(: data\).*")" ]; then
+	# it's a combined kernel and SquashFS image, the 'unsquashfs' utility has to locate the superblock first
 	stat="$(./unsquashfs4-le -stat -k "$fs" 2>&1)"
 	if [ -n "$(expr "$stat" : ".*\(Found a valid little endian\).*")" ]; then
 		endianess=le
@@ -40,16 +117,21 @@ elif [ -n "$(expr "$type" : ".*\(: data\).*")" ]; then
 		if [ -n "$(expr "$stat" : ".*\(Found a valid big endian\).*")" ]; then
 			endianess=be
 		else
+			rm "$fs" 2>/dev/null
 			exit 1
 		fi
 	fi
 fi
 
-rm -r ./squashfs-root 2>/dev/null
+rm -r "${tmp}/process_filesystem" 2>/dev/null
 
-./unsquashfs4-$endianess -k "$fs" etc 2>/dev/null 1>&2
+./unsquashfs4-$endianess -d "${tmp}/process_filesystem" -k "$fs" etc 2>/dev/null 1>&2
 
-extract_version_values ./squashfs-root
+/proc/self/exe $xtrace "$handler" "${tmp}/process_filesystem" $*
 
-rm -r ./squashfs-root 2>/dev/null
-
+#######################################################################################################
+#                                                                                                     #
+# end of script                                                                                       #
+#                                                                                                     #
+#######################################################################################################
+exit 0
