add new configuration files used by AVM and make some TFFS tools (for the box) POSIX-compatible

diff --git a/tffs/tbackup b/tffs/tbackup
--- a/tffs/tbackup
+++ b/tffs/tbackup
@@ -1,57 +1,94 @@
 #! /bin/sh
+find_executable()
+{
+	e="$1"
+	IFS=:
+	set -- $PATH
+	while [ ${#1} -gt 0 ]; do
+		[ -x "$1/$e" ] && return 0
+		shift
+	done
+	return 1
+}
+
 backup()
 {
 	for minor in $(seq 0 255); do
-		echo -n -e "\r\x1B[0KProcessing minor $minor (will go from 0 to 255) ..." 1>&2
+		printf "\r\x1B[0KProcessing minor $minor (will go from 0 to 255) ..." 1>&2
 		mknod $td/cdev c $major $minor
 		checkempty $td/cdev >/dev/null 2>&1
 		if [ $? -ne 0 ]; then
 			if grep -q '$$$$[A-Z1-6]*' $td/cdev 2>/dev/null; then
-				echo -n -e "\x1B[5m decoding content\x1B[25m" 1>&2
-				micro_decode $td/cdev >$td/$minor
-				decoded=",decoded=1"
+				if find_executable "decode_secrets" then
+					printf "\x1B[5m decoding content\x1B[25m" 1>&2
+					decode_secrets $td/cdev >$td/$minor
+					decoded=",decoded=1"
+				else
+					cat $td/cdev >$td/$minor
+					decoded=",contains_encrypted_data"
+				fi
 			else
 				cat $td/cdev >$td/$minor
 				unset decoded
 			fi
 			fsize=$(cat $td/$minor | wc -c)
-			echo "$minor" >>$td/files
-			echo -n -e "minor=$minor,size=$fsize$decoded\n" >>$td/minors
-			let used=used+fsize
+			printf "$minor\n" >>$td/files
+			printf "minor=$minor,size=$fsize$decoded\n" >>$td/minors
+			used=$(( used + fsize ))
 		else
-			echo -n -e "minor=$minor,size=0\n" >>$td/minors
+			printf "minor=$minor,size=0\n" >>$td/minors
 		fi
 		rm $td/cdev
 	done
-	echo -n -e "used=$used\n" >>$td/info
+	printf "used=$used\n" >>$td/info
 	cat $td/minors >>$td/info
-	echo -n -e "\r\x1B[0KCreating archive file from saved content ..." 1>&2
+	printf "\r\x1B[0KCreating archive file from saved content ..." 1>&2
 	cd $td
-	echo "info" >>$td/files
+	printf "info" >>$td/files
 	tar -c -C $td -f $td/tffs.tar -T $td/files
 	cd $popd
-	echo -n -e "\r\x1B[0KCompressing archive file ..." 1>&2
+	printf "\r\x1B[0KCompressing archive file ..." 1>&2
 	gzip -9 -c $td/tffs.tar
-	echo -n -e "\r\x1B[0K" 1>&2
+	printf "\r\x1B[0K" 1>&2
 }
 myself=$(realpath $0)
 myname=${myself##*/}
 mydir=${myself%/*}
-echo -n -e "\r\x1B[0KBacking up TFFS content ..." 1>&2
-td=/var/tmp/tbkp_$$_$(date +%s)
+printf "\r\x1B[0KBacking up TFFS content ..." 1>&2
+td=/tmp/tbkp_$$_$(date +%s)
 mkdir -p $td || exit 1
-#echo cleanup >/proc/tffs
-echo info >/proc/tffs
-major=$(grep tffs /proc/devices | sed -n -e 's/^\(.*\) .*/\1/p')
-mtd=$(grep '^mount=' /proc/tffs | sed -n -e 's/^.*=\(.*\)/\1/p' | sed -n -e ':x;N;$!bx;s/\n/ /p')
-set -- $mtd
-mtd_a=$1
-mtd_b=$2
-mtd_a_num=$(echo $mtd_a | sed -n -e 's/^mtd\(.*\)/\1/p')
-size=$(grep mtdblock$mtd_a_num /proc/partitions | sed -n -e 's/^.* .* \(.*\) .*/\1/p')
-let space=size*1024
-fill=$(grep '^fill=' /proc/tffs | sed -n -e 's/^.*=\(.*\)/\1/p')
-echo -n -e "major=$major\npart1=$mtd_a\npart2=$mtd_b\nsize=$space\nfill=$fill\n" >$td/info
+printf "cleanup\n" >/proc/tffs
+printf "info\n" >/proc/tffs
+major=$(sed -n -e 's/^\(.*\) tffs/\1/p' /proc/devices)
+if [ ${#major} -eq 0 ]; then
+	printf "\r\x1B[0KUnable to find the major device ID for TFFS driver.\n" 1>&2
+	exit 1
+fi
+mtd=$(sed -n -e 's/^mount=\(.*\)/\1/p' /proc/tffs | sed -n -e ':x;N;$!bx;s/\n/ /p')
+if [ ${#mtd} -gt 0 ]; then
+	type=spi
+	set -- $mtd
+	mtd_a=$1
+	mtd_b=$2
+	mtd_a_num=$(printf $mtd_a | sed -n -e 's/^mtd\(.*\)/\1/p')
+	size=$(sed -n -e "s/^ .* .* \(.*\) mtdblock$mtd_a_num\$/\1/p" /proc/partitions)
+	space=$(( size * 1024 ))
+else
+	mtd=$(sed -n -e "s/^\([^:]*\):.*tffs.*/\1/p" /proc/mtd)
+	if [ ${#mtd} -gt 0 ]; then
+		type=nand
+		size=$(sed -n -e "s/^$mtd: \([0-9a-f]*\).*nand-tffs.*/\1/p" /proc/mtd)
+		space=$(( 0x$size ))
+	else
+		type=unknown
+	fi
+fi
+fill=$(sed -n -e 's/^fill=\(.*\)/\1/p' /proc/tffs)
+printf "major=$major\n" >$td/info
+[ ${#mtd_a} -gt 0 ] && \
+	printf "part1=$mtd_a\npart2=$mtd_b\ntype=$type\n" >$td/info || \
+	printf "part=$mtd\ntype=$type\n" >$td/info
+printf "size=$space\nfill=$fill\n" >$td/info
 used=0
 popd=$(pwd)
 backup
diff --git a/tffs/tdel b/tffs/tdel
--- a/tffs/tdel
+++ b/tffs/tdel
@@ -1,32 +1,31 @@
 #! /bin/sh
 if [ -z $1 ]; then
-	echo "Usage: $0 <id>" 1>&2
-	echo "" 1>&2
-	echo "clear a TFFS file" 1>&2
-	echo "" 1>&2
-	echo "<id>       - TFFS character device minor id" 1>&2
-	exit 127
+	printf "Usage: $0 <id>\n\n" 1>&2
+	printf "clear the content of a TFFS file\n\n" 1>&2
+	printf "<id>       - TFFS character device minor id\n" 1>&2
+	exit 1
 fi
-tffs_major=$(grep tffs /proc/devices | sed -n -e 's/^\([0-9]*\) .*/\1/p')
-let i=$1 2>/dev/null
-if [ $? -ne 0 ]; then
-	i=0
+major=$(sed -n -e 's/^\([0-9]*\) tffs.*/\1/p' /proc/devices)
+if ! [ "$(expr "$1" : "\(^[0-9]*$\)")" = "$1" ]; then
+	printf "Non-numeric argument '%s' specified.\n" "$1" 1>&2
+	exit 1
 fi
-if [ $i -gt 0 -a $i -le 255 ]; then
-	tffs_minor=$i
+i=$1
+if [ $i -gt 0 ] && [ $i -le 255 ]; then
+	minor=$i
 	fn="/var/tmp/mknod_$$_$(date +%s)"
-	mknod $fn c $tffs_major $tffs_minor
+	mknod $fn c $major $minor
 	checkempty $fn 2>/dev/null
 	if [ $? -eq 1 ]; then
-		echo "clear_id $i" >/proc/tffs
+		printf "clear_id $i\n" >/proc/tffs
 		rc=0
 	else
-		echo "The file is empty already." 1>&2
+		printf "The file is empty already.\n" 1>&2
 		rc=1
 	fi
 	rm $fn
 	exit $rc
 else
-	echo "The specified minor id '$1' is invalid." 1>&2
-	exit 127
+	printf "The specified minor id '%s' is invalid.\n" "$1" 1>&2
+	exit 1
 fi
diff --git a/tffs/tvi b/tffs/tvi
--- a/tffs/tvi
+++ b/tffs/tvi
@@ -1,115 +1,126 @@
 #! /bin/sh
+find_executable()
+{
+	e="$1"
+	IFS=:
+	set -- $PATH
+	while [ ${#1} -gt 0 ]; do
+		[ -x "$1/$e" ] && return 0
+		shift
+	done
+	return 1
+}
+
 if [ -z $1 ]; then
-	echo "Usage: $0 <filename | id>" 1>&2
-	echo "" 1>&2
-	echo "View/edit a TFFS file" 1>&2
-	echo "" 1>&2
-	echo "<filename> - file name within /var/flash directory" 1>&2
-	echo "<id>       - TFFS character device minor id" 1>&2
-	echo "" 1>&2
-	echo "The file content will be copied to a temporary file, 'vi' will be called for it and" 1>&2
-	echo "it will be copied back after user committed intentional changes to the file." 1>&2
-	echo "If the changed content is related to 'ctlmgr' (e.g. it's a .cfg file at /var/flash), you" 1>&2
-	echo "will be asked to restart 'ctlmgr'." 1>&2
-	exit 127
+	printf "Usage: $0 <filename | id> [ --no-decode ]\n\n" 1>&2
+	printf "View/edit a TFFS file\n\n" 1>&2
+	printf "<filename> - file name within /var/flash directory\n" 1>&2
+	printf "<id>       - TFFS character device minor id\n\n" 1>&2
+	printf "The file content will be copied to a temporary file, its content will be decrypted, if the\n" 1>&2
+	printf "needed binary (decode_secrets) exists and 'vi' will be called for it.\n\n" 1>&2
+	printf "It will only be copied back after user made *intentional* changes to the file.\n\n" 1>&2
+	printf "If the changed content is related to 'ctlmgr' (e.g. it's a .cfg file at /var/flash), you\n" 1>&2
+	printf "will be asked to stop 'ctlmgr' while storing the new data.\n" 1>&2
+	exit 1
 fi
-tffs_major=$(grep tffs /proc/devices | sed -n -e 's/^\([0-9]*\) .*/\1/p')
-let i=$1 2>/dev/null
-if [ $? -ne 0 ]; then
-	i=0
-fi
-if [ $i -gt 0 -a $i -le 255 ]; then
-	tffs_minor=$i
+major=$(sed -n -e 's/^\([0-9]*\) tffs.*/\1/p' /proc/devices)
+[ "$(expr "$1" : "\(^[0-9]*$\)")" = "$1" ] && i=$1 || i=-1
+if [ $i -gt 0 ] && [ $i -le 255 ]; then
+	minor=$i
 	fn="/var/tmp/mknod_$$_$(date +%s)"
-	mknod $fn c $tffs_major $tffs_minor
-	rmf=$fn
+	mknod "$fn" c $major $minor
+	rmf="$fn"
 else
 	fn="$1"
 	dir=/var/flash
-	if [ -c $dir/$fn ]; then
-		tffs_minor=$(( 0x$(stat -c %T $dir/$fn) ))
+	if [ -c "$dir/$fn" ]; then
+		minor=$(( 0x$(stat -c %T "$dir/$fn") ))
 		fn="$dir/$fn"
 	else
-		echo "The specified file '$fn' isn't a character device at '$dir'."
-		exit 127
+		printf "The specified file '%s' isn't a character device at '%s'.\n" "$fn" "$dir" 1>&2
+		exit 1
 	fi
 	unset rmf
 fi
-tf=$(echo /var/tmp/temp_$$_$(date +%s))
-cat $fn | gunzip -c >$tf 2>/dev/null
+tf="/var/tmp/temp_$$_$(date +%s)"
+find_executable "decode_secrets" && decode="decode_secrets" || decode="cat"
+[ "$2" = "--no-decode" ] && decode="cat"
+cat "$fn" | gunzip -c 2>/dev/null 1>&2
 if [ $? -ne 0 ]; then
-	cat $fn >$tf
+	$decode <"$fn" >"$tf"
 	zip=0
 else
+	cat "$fn" | gunzip -c | $decode >"$tf"
 	zip=1
 fi
-cks_before=$(md5sum <$tf | sed -n -e 's/^\([0-9a-f]*\).*/\1/p')
-vi $tf
-cks_after=$(md5sum <$tf | sed -n -e 's/^\([0-9a-f]*\).*/\1/p')
-if [ "$cks_after" != "$cks_before" ]; then
+cks_before=$(md5sum <"$tf" | sed -n -e 's/^\([0-9a-f]*\).*/\1/p')
+vi "$tf"
+cks_after=$(md5sum <"$tf" | sed -n -e 's/^\([0-9a-f]*\).*/\1/p')
+if ! [ "$cks_after" = "$cks_before" ]; then
 	error=2
 	while [ $error -eq 2 ]; do
-		read -n 1 -p "The file was changed. Do you want to commit the changes to TFFS ? (y/N): " answr
+		printf "The file was changed. Do you want to write the changes to TFFS ? (y/N): " 1>&2
+		read answr
 		if [ ${#answr} -eq 0 ]; then
 			answr='n'
 		fi
-		if [ "$answr" == "Y" -o "$answr" == "y" ]; then
+		if [ "$answr" = "Y" ] || [ "$answr" = "y" ]; then
 			fe="${fn#*.}"
-			if [ "$fe" == "cfg" ]; then
+			if [ "$fe" = "cfg" ]; then
 				restart=2
-				echo "" 1>&2
 			else
 				restart=0
 				restartmsg=" not"
 			fi	
 			while [ $restart -eq 2 ]; do
-				read -n 1 -p "Do you want to restart 'ctlmgr' to activate your changes ? (y/N): " answr
+				printf "Do you want to restart 'ctlmgr' to activate your changes ? (y/N): " 1>&2
+				read answr
 				if [ ${#answr} -eq 0 ]; then
 					answr='n'
 				fi	
-				if [ "$answr" == "Y" -o "$answr" == "y" ]; then
+				if [ "$answr" = "Y" ] || [ "$answr" = "y" ]; then
 					restart=1
 					restartmsg=""
 				else
-					if [ "$answr" == "N" -o "$answr" == "n" ]; then
+					if [ "$answr" = "N" ] || [ "$answr" = "n" ]; then
 						restart=0
 						restartmsg=" not"
 					else
-						echo -e "\nPlease choose 'y' or 'n' and answer again ..." 1>&2
+						printf "\nPlease choose 'y' or 'n' and answer again ...\n\a" 1>&2
 					fi
 				fi
 			done
 			if [ $restart -eq 1 ]; then
-				echo -n "Stopping ctlmgr ... " 1>&2
+				printf "Stopping ctlmgr ... " 1>&2
 				ctlmgr -s
-				echo "done, error = $?"
+				printf "done, error = $?"
 			fi
 			if [ $zip -eq 0 ]; then
-				cat $tf >$fn
+				cat "$tf" >"$fn"
 			else
-				gzip -c $tf | cat >$fn
+				gzip -c "$tf" | cat >"$fn"
 			fi
-			echo -e "\nChanges saved." 1>&2
+			printf "\nChanges saved.\n" 1>&2
 			error=0
 			if [ $restart -eq 1 ]; then
-				echo -n "Starting ctlmgr ... " 1>&2
+				printf "Starting ctlmgr ... " 1>&2
 				LD_LIBRARY_PATH= ctlmgr
-				echo "done, error = $?"
+				printf "done, error = $?\n" 1>&2
 			fi
-			eventadd 1 "The configuration file with minor ID $tffs_minor was changed and ctlmgr was$restartmsg restarted."
+			eventadd 1 "The configuration file with minor ID '$minor' was changed and ctlmgr was$restartmsg restarted."
 		else
-			if [ "$answr" == "N" -o "$answr" == "n" ]; then
-				echo -e "\nThe changes were not saved." 1>&2
+			if [ "$answr" = "N" ] || [ "$answr" = "n" ]; then
+				printf "\nThe changes were not saved.\n" 1>&2
 				error=1
 			else
-				echo -e "\nPlease choose 'y' or 'n' and answer again ..." 1>&2
+				printf "\nPlease choose 'y' or 'n' and answer again ...\n" 1>&2
 			fi
 		fi
 	done
 else
-	echo "The file was not changed." 1>&2
+	printf "The file was not changed.\n" 1>&2
 	error=1
 fi
-rm $tf
-[ ${#rmf} -gt 0 ] && rm $rmf
+rm "$tf"
+[ ${#rmf} -gt 0 ] && rm "$rmf"
 exit $error
